### ISSUE TITLE
Automatically restore keybindings when vrapper is disabled

### ISSUE THREAD

**Issue by fidesachates** [vrapper/vrapper#108]
It would be nice if vrapper could save the key bindings that users have to disable to get their preferred vim key mappings working. When the toggle vrapper button is released, it should restore the key bindings. 

E.g. if .vrapper configuration file has the following to map CTRL-A to beginning-of-line 
imap <C-a> 0

Then while vrapper was enabled, user disables the key binding for CTRL-A in eclipse to mean "select all". After vrapper is disabled, the key bindings for CTRL-A to "select all" is restored in eclipse. 

The implementation might be a bit crude, but any solution that provides the goal of restoring key bindings that were disabled for vrapper to work is the goal.

**Comment by albertdev** [comment]
I was at home this week thanks to the flu. While I couldn't get that much done, it did give me time to read about Eclipse's command and handler frameworks. What I'm currently thinking of is not to disable Eclipse key bindings but to override them.

When you assign key bindings in Eclipse's preferences, you have to configure a so-called context (e.g. "Editing Java", "Editing Text", "Editing C/C++", ...) and several different editors will enable and disable these contexts to allow certain key binds. What we could try to do is make a Vrapper context which somehow takes higher priority than the original ones and only enable this context when Vrapper is also active. Assigning binds to this context would thus override the default ones, and disabling the context will suddenly allow the original ones to work.

We could even allow multiple contexts (insert, normal, visual, ...) if we want to get really fancy, but I still need to get this working first.

**Comment by albertdev** [comment]
People who are interested in this might want to read the comments in #820: we now have something in our Unstable Update Site through which you can bind keys for Vrapper without ever touching your existing Eclipse shortcuts.

Because these Vrapper shortcuts can be made conditional (i.e. "Vrapper is Enabled", "Vrapper in Normal mode", "Vrapper in Insert mode", ...) you can even bind things to a specific Vrapper mode. And when you disable Vrapper or change mode, all your original shortcuts will still work. Finally you can share your Eclipse install again for pair-programming.
