### ISSUE TITLE
Add support for gf

### ISSUE THREAD

**Issue by dhallas** [vrapper/vrapper#114]
Add support for the 'gf' command, see: http://vimdoc.sourceforge.net/htmldoc/editing.html#gf for details.

**Comment by ceinmart** [comment]
Hi!
Isn't possible to create a vrapper parameter to set the gf behave?
If they should work with absolute path or relative path , either both... try one first, then other... 
Here I use the vrapper with Dbeaver sql client (dbeaver.io) , so , I haven't project , all file names which appear on my .sql files are absolute path.

**Comment by keforbes** [comment]
I'm sorry, but adding support for absolute path would actually require a lot of extra work (as I mentioned 10 years ago).  Eclipse abstracts the local file system so `/` is the project root and all files live within that namespace (this is what Vrapper has implemented).  Accessing external files as they exist on disk would require adding another Eclipse library as a Vrapper dependency (`org.eclipse.core.filesystem`) which Vrapper currently doesn't use.  After that, I think it'd be possible to access files on the _local_ mount point (no NFS, no domains) starting at the actual root `/`.  If you're on Windows though, I don't know if it'd be possible to hardcode `C:\` or somehow support other drive letters.

The way things are implemented now, Vrapper uses the `path` config param to determine where to look for the filenames provided by `gf`.  You can use a value of `/` in the path to represent "the entire Eclipse project" because Eclipse uses `/` as the path delimiter (it's a URI, not a file location).  If we somehow implemented absolute paths, I can't set `""` as the root search directory but I also can't assume a root of `/` or `C:\` or `D:\`.

This adds a lot of extra effort and complexity for something which I believe is a corner case and wouldn't get much use.  Keep in mind, I implemented this feature 10 years ago and this is the first time it's been requested.  Sorry.
