### ISSUE TITLE
:new command in vrapper

### ISSUE THREAD

**Issue by l0l1l2l3l2l1l0l** [vrapper/vrapper#265]
i`m sorry to leave this question on this forum but, 

is there any way i can use :new command in vrapper? 

i searched your documentation and googled about it but i really cannot find a way. 

ps : i found :split is really working well.

**Comment by clyton** [comment]
@igrekster @justinmk Could you help me with finding eclipseactions. The method you suggested of exporting key preferences does not work. I get a very small file. It does not have all the default keybindings.
This is what gets exported:
/instance/org.eclipse.ui.workbench/org.eclipse.ui.commands=<?xml version\="1.0" encoding\="UTF-8"?>\n<org.eclipse.ui.commands/>
@org.eclipse.ui.workbench=3.110.0.v20170612-1255
file_export_version=3.0

**Comment by igrekster** [comment]
@clyton Yep, I usually bind the action I want to something very long but searchable  (like `Ctrl+Shift+Alt+X`) and then export. Alternatively this method works as well http://evans-stuff.blogspot.com.au/2007/10/it-seems-that-im-not-only-one-still.html
What specific action are you looking for?

**Comment by clyton** [comment]
I was looking for the showView command (Alt+Shift+X) and then by pressing a single letter jump to the desired view. For eg: Alt+Shift+X C will jump to console view. I wanted to bind it to <leader>sv. 
But now I realize that this is not of much use because the vrapper functionality will not work in any other view apart from the editor.
