### ISSUE TITLE
insert mode mapping problem

### ISSUE THREAD

**Issue by gvinterhalter** [vrapper/vrapper#359]
Hello all, I'm using vrapperr 0.38.0 and the problem is that if I do for example
`:ino jj <ESC>
`
and type for example "hello worldjj" I get "hello worldj" Notice the 'j' at the end.
For some reason one 'j' always remains and I have several mappings that
relay on similar combinations. Am I missing something is this normal behavior ?

For now I'm forced to do `:ino jj <ESC>"_x`  
which is ugly  and I get history for that delete, I tried with `<C-g>u` but then
the whole line disappears. I'm hopping that this is just  some misunderstanding from my side.

**Comment by idealvin** [comment]
Take a look at #669 #670

**Comment by albertdev** [comment]
@idealvin 
While your conclusion is correct for the current problems, this particular issue was caused by something else and happened even when you entered just `jj`.

Basically, Vrapper inserts the first `j` to show what the user has typed already, but the `softtabstop` setting would interfere with the cleanup of that first character. Therefore you would be left with extra characters in your file which is obviously annoying.

It took us a while to realize it was the `softtabstop` setting...
