### ISSUE TITLE
vrapping egit eclipseactions

### ISSUE THREAD

**Issue by Konfekt** [vrapper/vrapper#428]
Can vrapper map the EGit actions?

For example the naive tries

```
eclipseuiaction Commit org.eclipse.egit.ui.team.Commit
eclipseuiaction OpenCommit org.eclipse.egit.ui.team.OpenCommit
```

did not work over here. As these commands are well nested in the context menu of the current project in the project explorer, these would save a lot of clicks.

**Comment by albertdev** [comment]
I'm going to close this issue after having troubleshooted a similar error.

Either there was a typo in the command name or EGit is disabling its handlers because it expects a file to be selected in some EGit view or the Project Explorer.

There's not really anything we're going to be able to do about that, instead people should ask the EGit team for a command which can be bound to a Keyboard shortcut that's triggerable without any active selection. That way Vrapper could simply use *that* command and be done with it.
