### ISSUE TITLE
Lost focus after `:split` and `:q`

### ISSUE THREAD

**Issue by sq6jnx** [vrapper/vrapper#435]
Hello,

I'm not sure if this is Vrapper's or Eclipse's problem, but I've noticed that after closing split (`:q`) no editor window has focus. I don't experience such problem when closing tab (`gt` followed by `:q`).

**Comment by dennis97519** [comment]
Still bugged til this day :(

**Comment by Droj** [comment]
>_something_ in the workbench steals our focus

What's interesting is that, usually, when the focus is "somewhere else", I can just hit F12/"Activate Editor" to get back. When this happens after splitting, _no_ keys will do anything (except for holding "Alt" to get to menus, which really doesn't help at all). I've never observed unrecoverable focus w/ any other situation or plugin.

Incidentally, I'm also seeing this behavior after splitting the frame by dragging a tab.

(Running 0.72 on Eclipse Neon)

**Comment by albertdev** [comment]
@Droj I believe the trouble still is that Eclipse seems to focus some unknown object related to the editor but not the editor itself, and Vrapper will likely not get triggered when there's no editor focused. There's not much we might be able to do about it, especially if you can reproduce it when dragging a tab.

The only "thinking outside the box" solution I can come up with at this moment is implementing our own global "Activate Editor" command which would do some more effort to actually restore focus to the right item. Though that's without checking how hard it would actually be... 😕

**Comment by Droj** [comment]
@albertdev, thanks for mentioning the mouse... It got me thinking. It turns out that I can reproduce this with vanilla Eclipse (i.e. no Vrapper). Adding or removing a split in the editor view causes all keyboard entry to be lost, except for the top menu. 

My only options are to click the mouse, or use the keyboard to select a menu item. The most useful menu option I've found is: 

* Window > Navigation > Next View
* \<up\> to go back to "Editor"
* \<enter\>

So, to restore editor focus w/o the mouse: \<Alt-W\>gv\<Up\>\<Enter\>

Technically, this is not a Vrapper issue. _However_, since Vrapper is creating the new split via a keyboard command, it would reasonable for it to do what's needed to keep focus in the editor (and our hands on the keyboard :) ).

Maybe this workaround of selecting the editor "view" is a potential path...?

**Comment by albertdev** [comment]
I had an itch to get this one resolved. The only thing holding me back in the past was that people might want to bind it to <kbd>Esc</kbd> and hence would complain if pressing <kbd>Esc</kbd> would no longer do anything in Vrapper.

The usual way to do something like this is make a shortcut handler with a condition. This is what the default shortcut for "Activate Editor" is using, and it simply checks that the shortcut becomes active when you switch to a View, then it becomes inactive when it has switched to the editor. Trouble is, in the issue reported in this ticket still happens when an editor is selected, it's just that the focus got lost. There's not really any efficient way to track the focus like that (see my comment above about my fear of getting in a loop of focus-stealing).

I'm currently experimenting with an alternative approach: I've added a shortcut which remains always available and will switch to the editor like the built-in command does. Then I try to look up if the current editor has Vrapper initialized, force the focus on the text editor associated with it and "replay" the key which was used to trigger the shortcut for Vrapper or whatever plugin is listening.

The latter two bits are the scary parts (which is why I haven't pushed this to the repo yet):
* Forcing the focus might theoretically backfire if a modal dialog is open and you trigger the shortcut. I don't know yet if it's a real issue or if the focus can actually be easily restored.
* The "replay" part took some digging in the Eclipse API. At first I would simply clone the keypress event and send it on, but then Eclipse would enter my shortcut handler again, which would trigger Eclipse, which would trigger the shortcut, and so on, until we get a stack overflow. As a workaround it now entirely toggles off the Eclipse keyboard handling for the duration of the replay event. I really hope that doesn't cause too much issues...

**Comment by albertdev** [comment]
The fix is now in our Unstable Update Site. Make sure that in the Keyboard shortcuts "Activate Editor and Type" is bound to <kbd>Esc</kbd>, then press it whenever the focus got lost.
