### ISSUE TITLE
IRC, Chat?

### ISSUE THREAD

**Issue by hrj** [vrapper/vrapper#575]
Sorry, this is a little offtopic, but I don't know how else to contact you.

I have been recently filing some silly bugs / feature-requests. It would be good if there was a chat channel where I (and others) could sound their concerns before filing issues here. It's kind of easier to sort things out.

Two suggestions come to mind:
1. an IRC channel on freenode (slightly difficult to setup but used widely)
2. gitter.im (very easy to setup, and just requires Github auth)

If you need any help in setting up; let me know.

**Comment by dabro** [comment]
Hey, you might want to reconsider the above.  I've been using Gitter for about two weeks, and it's working well with minimal effort.  I get notices in my email, and they have mobile apps now (I use Android, get notices on my main screen).  Seems to work well for the projects I'm monitoring, and doesn't require an intensive IRC setup.

**Comment by keforbes** [comment]
Ok, I agree with you.  I've seen Gitter on more projects lately and it does look pretty helpful.  It certainly doesn't hurt anything for it to exist even if no one posts to it.

I did my best to create a public room but it seems like you can't see the messages unless you login to Github.  If someone knows how to make the room visible to everyone let me know.  Otherwise, it looks like it's public after you login.

**Comment by albertdev** [comment]
I was able to join, but then again I'm part of the vrapper organization. We'll see if @dabro or @hrj can join...
