### ISSUE TITLE
Switching between visual-blockwise and other visual modes resets selection

### ISSUE THREAD

**Issue by albertdev** [vrapper/vrapper#576]
Vim allows to toggle between all possible visual modes while keeping the "starting position" and "current position" fixed so that the selection updates itself.

Vrapper on the other hand resets the selection to one character if visual mode is entered, or it resets to the line on which the starting position was if switching to linewise visual mode.

**Comment by solde9** [comment]
I've traced the problem to this line 
https://github.com/vrapper/vrapper/blob/master/net.sourceforge.vrapper.core/src/net/sourceforge/vrapper/vim/modes/BlockwiseVisualMode.java#L324
Obviously, removing this line allows to toggle between blockwise selection, but this hack was preventing a bug: 2f4bdd59f4f344a68fe73c613badd02346c5aef5 
I wonder if there is some way to prevent this bug without clearing the selection.

**Comment by solde9** [comment]
I think I might have a solution. `ITextViewer` has a method to toggle blockSelection on and off. I will add a new method in `CursorService` to add this functionality. This will allow fixing the bug without clearing the selection.

**Comment by albertdev** [comment]
Please don't. Your previous comment was correct; clearing the selection there is wrong but introducing all kinds of new Platform hooks seems to be the wrong way.

What should happen IMHO is a rewrite of the `ChangeOperation`: the normal / visual code should stay and the visual block stuff should be moved to a `ChangeBlockCommand`. This new class can then clear the selection any way it wants to, all the regular stuff will still work.

**Comment by solde9** [comment]
@albertdev Maybe you are right. My intention was to add this method because currently there is no isolated way of setting off the block selection without nulling the selection. For example, there is a call here: https://github.com/vrapper/vrapper/blob/master/net.sourceforge.vrapper.eclipse/src/net/sourceforge/vrapper/eclipse/platform/EclipseCursorAndSelection.java#L257
Because of that line is why nulling the selection restore the cursor after leaving `BlockwiseMode`. What I thought was that `CursorService` will need to have a method with this alone:
```java
textViewer.getTextWidget().setBlockSelection(blockSelectionBoolean);
```
I've tested and it works but I agree with you that maybe a rewrite is a better option.
Let me know if you want me to create that PR just for the purpose of showing what I'm trying to say. You can close it after anyway.

**Comment by keforbes** [comment]
This fix is in the latest unstable build but since @albertdev is the one who filed it I'm not sure if anyone was really waiting on the fix...

Thanks for fixing it though! :smile:
