### ISSUE TITLE
Clear hlsearch pattern

### ISSUE THREAD

**Issue by sschaef** [vrapper/vrapper#577]
With `:let @/ = ""` the search pattern that is highlighted can be cleared in vim. In vrapper it doesn't seem to be supported (clearing other registers like `"0` doesn't make any problems).

**Comment by keforbes** [comment]
Ha, I had no idea we supported `:nohlsearch`!  It was never documented even though it's been there since before I joined the project.  I'll add it to the docs. :)

**Comment by adelarsq** [comment]
Cool feature. I did a map on Vim to use this =)
```
nnoremap <Esc><Esc> :let @/ = ""<cr>
```

**Comment by albertdev** [comment]
I've been thinking some more about this one but currently Vrapper's internal behaviour is too different from Vim to simply port it.

@sschaef, @loonies, @adelarsq, @keforbes 
What do you think of the following proposition?

* Each window keeps its own highlighting under normal use. For example, when you first search for "foo" in window 1 and then window 2, both windows will highlight "foo". If you go back to window 1 and search for "bar", the highlighting in window 1 changes but no change will occur in window 2 until you switch to it and press `n` (after all, the search register is shared between the two if `globalregisters` is set). The reason for this is that updating the highlighting is slow.
* Running `:nohlsearch` or `:let @/=''` immediately clears highlighting in all editors if `globalregisters` is set, otherwise it's local.
* To fix the "highlighting suddenly pops up when opening a new editor" problem, I think I have to refactor Vrapper's configuration from once per editor to once per Eclipse startup. This does fix another issue, which is that loading a new editor would override your current global settings if your `.vimrc` contains `set` instructions instead of `setlocal`. On the other hand, every `setlocal` in your `.vimrc` except for autocommands would become ineffective, and remappings would only be loaded at startup instead of being reloaded if you reopen an editor.

**Comment by loonies** [comment]
> Each window keeps its own highlighting under normal use. For example,
> when you first search for "foo" in window 1 and then window 2, both
> windows will highlight "foo". If you go back to window 1 and search
> for "bar", the highlighting in window 1 changes but no change will
> occur in window 2 until you switch to it and press n (after all, the
> search register is shared between the two if globalregisters is set).
> The reason for this is that updating the highlighting is slow.

I think the proposed solution could be confusing with window splits, or
when switching to window 2 after 2nd search. Could you make it
configurable? I propose three possible configuration values:

 - Update search highlight "globally" (as Vim does) - performance hit,
   more user friendly
 - Keep previous search highlight (as you proposed) - save performance,
   a bit confusing with splits, window switching
 - Clear search highlight from all the other windows - save performance,
   less confusing

This way we can choose behaviour that fits us the best.

> Running :nohlsearch or :let @/='' immediately clears highlighting in
> all editors if globalregisters is set, otherwise it's local.

:+1:

**Comment by adelarsq** [comment]
I think that being possible to configure the behavior is better. By the way, I prefer update search highlight "globally".
I agree with the second and third proposals :+1:

**Comment by albertdev** [comment]
Small update: I introduced a new (global) string setting `hlscope` similar to @loonies proposal:

* Set to `window`, starting a search or pressing `n`/`N` will trigger highlighting in all active editors in the current window. If any of them have `noglobalregisters` set, those will use the last search keyword used in that given editor. Clearing highlighting using `:nohlsearch` clears everything. I don't know if there is any need to let it spread to editors in another Eclipse window within the same session (Vim has no multi-GUI-window support built-in).
* Set to `clear`, only one editor can have highlighting. Switching between editors does nothing, but doing a search will clear all highlighting from all editors and only activate it in the current editor. `:nohlsearch` clears everything including the current editor.
* Set to `local`, each editor has independent highlighting. `:nohlsearch` will never touch highlighting in other editors.

Note that I also changed `hlsearch` into a global variable. Keeping it's global-local behavior would grow too complex, and the `hlscope` feature better explains what is happening.

I haven't started on `let @/=''` yet though, I'm thinking whether I should just hack it in or take the opportunity to re-implement the `let` command as a more flexible configuration framework for plugins...

**Comment by albertdev** [comment]
Alright, I went for the "short hack" route as it would otherwise take me ages to come up with a feature nobody on the short term will use. I did allow `let @/="new search term"`, it will try to create a new search query and change the highlighting. Passing an empty string will clear highlighting as requested.

For now I put the default `hlscope` value to `clear`: only one editor will keep its highlighting. Please give some feedback of how the `local` and `window` values work out for you guys once this makes it to the unstable site.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150219) which includes this change.  Please test it out and let us know if you run into any issues.  Thanks!

**Comment by keforbes** [comment]
@albertdev, could you update the docs with `let` and `hlscope`?  It'd probably be best if you described them. :)

**Comment by albertdev** [comment]
@keforbes  I'll look at it in the course of next week.

**Comment by loonies** [comment]
Thanks for this implementation! Also, thanks for implementing
`let @/=""`, it works excellent. Clearing search highlighting doesn't annoys
any more.

Couple of issues I've found:

**set hlscope=window**

After a "cold" Eclipse start search only highlights the current tab and
the split. There is no highlighting in other tabs. Splitting
non-highlighted tab triggers highlighting. Any subsequent search, tab
switch, window split works as expected.

**set hlscope=local**

Works as expected.

**set hlscope=clear**

After a "cold" Eclipse start search highlights a search string in
another tab of the same editor (switch from 1st tab to 2nd). There is no
highlighting after switching back to 1st tab. I'm not sure how is this
working TBH.

**Comment by albertdev** [comment]
@loonies
I don't highlight any editors which you haven't used yet because Vrapper is simply not initialized in those editors. I'll check if this is the case if your workbench contains two editors in a split.

It's highly likely though that this is another side-effect of #592 due to the changed code - switching might suddenly trigger Vrapper initialization, altering the highlighting even when you didn't want it to.

I will try out your scenarios, thanks for your feedback.

**Comment by albertdev** [comment]
@loonies 
I have been doing some further testing and you're right, the behaviour is somewhat off. It looks like there are listeners firing when a new editor gets initialized, but these listeners don't pick up the current (half-initialized) editor.

**Comment by albertdev** [comment]
Ok, the next unstable or release build should work better - the `hlscope` default is still "clear" but it doesn't change the other editor. Setting it to "window" will now properly initialize the highlighting for each editor like Vim does, `let @/=""` will clear it for all.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150402) which includes @albertdev's latest fix.  Give it a try and let us know how it goes.
