### ISSUE TITLE
LGPL license?

### ISSUE THREAD

**Issue by drusifer** [vrapper/vrapper#580]
I'm not sure if you've considered this but is it possible to change your license from the GPL to the LGPL or perhaps the Eclipse Public License?  This would make it much simpler to use this plugin in a commercial context since eclipse is not itself GPL'd. See http://en.wikipedia.org/wiki/Eclipse_Public_License for more info on EPL.

**Comment by albertdev** [comment]
@drusifer 
Suppose we do go for a GPL with exceptions for EPL-licensed binaries and free linking with Eclipse, would that satisfy your use case?

The way I see it you are then free to distribute any combination of Vrapper plugins and Eclipse plugins without the whole thing becoming GPL, it's only stuff using Vrapper's APIs which would.

**Comment by drusifer** [comment]
Happy New Year!   I'm trying to get some clarification on my end to see if an updated GPL license with exceptions would be okay.  I'll let you guys know what I find out.

BTW another option would be to dual-license Vrapper.  So you can release it under both GPL and EPL and/or LGPL.

**Comment by keforbes** [comment]
I'm sorry for being dense, but can you explain why you can't use a GPL'd plugin?  Are you releasing/redistributing Vrapper as a part of some bundle?

**Comment by drusifer** [comment]
No, the problem is that we are internally distributing our own proprietary eclipse plugins.  Because GPLv3 is not compatible with EPL (or our own license) we can't use Vrapper and our plugins together (without our plugins becoming GPL'd).

**Comment by keforbes** [comment]
I don't think that's true... Are you saying if I have Adobe Flash Builder or IBM Rational Software Architect (both proprietary, closed-source tools built on Eclipse) and I install the Vrapper plugin, Adobe and IBM must therefore release their source code?  I don't think installing two separate plugins which don't interact with each other constitutes a derivative work.

I guess I still don't see how this is an issue but I'm not a lawyer.  All I can say is that I promise I won't sue you for installing Vrapper.  ;-)

**Comment by albertdev** [comment]
@keforbes 
IANAL, but the Free Software Foundation does believe that the whole [combined set of plugins and program needs to be GPL](http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF):

> If the program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single program, which must be treated as an extension of both the main program and the plug-ins. This means that combination of the GPL-covered plug-in with the non-free main program would violate the GPL. However, you can resolve that legal problem by adding an exception to your plug-in's license, giving permission to link it with the non-free main program.

While you do want some protection for the case derivative work turns up, the combined work should now also be GPLed unless explicitly excluded. The downside to excluding is we would create a "Vrapper license", which might not be GPL-compatible anymore (i.e. you might then not use any GPL libraries unless they actually use our custom license). The latter might be a drawback, but currently no Vrapper user is allowed to distribute his Eclipse because he's made an illegal mixture of GPL and EPL binaries, so something needs to be done.

At the end of the day, the "Vrapper is not for sale" standpoint is moot. GPLed code can be modified and sold, it's just that *every* download of the binary means that it should come with (access to) the modified sources. LGPL or EPL licensed just change this by allowing closed-source extensions, but if that's fine they can be considered for use by Vrapper.

**Comment by drusifer** [comment]
Thanks @albertdev that just about sums up my issue.  For us to use Vrapper with our version of Eclipse we would need it to be under the LGPL or EPL, or one of the other less restrictive opensource licenses.  I don't know if there are other users in the same boat but it would sure help me out a lot if you guys could make the switch.

**Comment by drusifer** [comment]
Hey guys, just checking in.  What are your thoughts on dual licensing?

**Comment by albertdev** [comment]
I haven't heard from @keforbes about this issue.

Dual licensing has the same caveat as modifying Vrapper's license: every contributer needs to give permission to use that new license. It's also more work as we would need two sets of source releases: one with e.g. LGPL clause at the top of each file and one with e.g. the MPL at the top.

**Comment by keforbes** [comment]
I'm sorry, but I'm still not seeing an issue here.  The quote @albertdev pasted mentions a "non-free main program" using a GPL plugin.  This is not your scenario.  You guys have a free main program (Eclipse) with your non-free plugin.  I still don't think installing a free plugin (Vrapper) next to your non-free plugin would affect anything.  They don't interact or communicate.  It's an end-user customization, not something used by (or distributed with) your product.

Even with that said, there are closed-source proprietary tools (Adobe Flash Builder, IBM Rational Software Architect) which are built on Eclipse.  You can install Vrapper on those tools without requiring Adobe or IBM to release their source code.  Those tools don't depend on Vrapper or redistribute Vrapper, you can just install Vrapper with them if you want.  As long as you aren't shipping Vrapper as part of your proprietary Eclipse, I don't see how choosing to install Vrapper as a plugin after-the-fact would violate any licensing of your product.

While I appreciate your concern, I think you should just use Vrapper and don't worry about it.  I don't think it's worthwhile for us to try tracking down every single contributor Vrapper has seen in order to change our licensing scheme just to help out one person who has a plugin they distribute internally.  I don't see any reason for us to change our licensing scheme; I don't think we're preventing you from doing anything.  I'm sorry, I'm not trying to be a jerk about this, I just don't think it's worth worrying about or spending any effort on.  I don't think you're violating anything by installing Vrapper.

**Comment by albertdev** [comment]
@keforbes
Eclipse is not GPL-compatible and thus I *think* that it is "non-free" from the perspective of our license. I am not a lawyer though, and I must confess that the FSF can be a bit stubborn at times in the way they look at the world.
