### ISSUE TITLE
Some remaps cause a stack overflow in the plugin

### ISSUE THREAD

**Issue by OlivierLi** [vrapper/vrapper#598]
For example : 
nmap n nzz

**Comment by albertdev** [comment]
If you mean that recursive macros cause a stack overflow: that's already reported in #509.

However, you seem to bring up an interesting case. I thought this same map in Vim would keep on searching until you hit the end, but it seems Vim has something built-in to detect common remaps and make them non-recursive (most likely if it sees that you're remapping to the original key + something extra). You can see this if you do `nmap n jnzz` in Vim; it will keep on scrolling till you hit the end because the mapping becomes recursive.

I think this special case is not too hard to detect. At least it's simpeler than fixing #509. Can you check if your other failing remaps are of the same type?

As a workaround, you can also try to do `nnoremap n nzz`, that should technically do the same.

**Comment by OlivierLi** [comment]
My other remap was nmap N Nzz. So basically the same thing.

Thank you for the workaround!

**Comment by albertdev** [comment]
This is rather low-hanging fruit so I went and implemented some code for it. Whenever Vrapper detects that you have something like `nmap <input> <input><extra chars>` it will change the command to the non-recursive `nnoremap` version and print a warning in the bottom-left status area.

This will be included in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150219) which includes this fix.  You can install it and test it out or continue using your `nnoremap` workaround.  They should both have the same behavior.

**Comment by OlivierLi** [comment]
Thanks again!I wish there was a way to tip you guys.Vrapper makes my days spent in Eclipse much better!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: keforbesSent: Thursday, February 19, 2015 23:28To: vrapper/vrapperReply To: vrapper/vrapperCc: Olivier LiSubject: Re: [vrapper] Some remaps cause a stack overflow in the plugin (#598)I've updated the unstable update site with a new build (0.53.20150219) which includes this fix.  You can install it and test it out or continue using your nnoremap workaround.  They should both have the same behavior.

—Reply to this email directly or view it on GitHub.
