### ISSUE TITLE
Can't pass filename to shell command

### ISSUE THREAD

**Issue by pa0los** [vrapper/vrapper#599]
I tried running (in Windows):
`:.!cmd /c echo %`
This should print me the file name, but I get only '%' instead.

**Comment by albertdev** [comment]
Nobody asked for it before so that expansion wasn't implemented. I think the original usage was for stdin/out filtering.

Marking this as a feature request. It shouldn't be too hard to change the PipeExternalOperation to do such a replacement.

**Comment by keforbes** [comment]
This was a simple change but I'm not sure if it'll work the way you want.  In Vrapper's `EclipseFileService.java` I explicitly prefix all paths with `/` for the project root.  I can't remember why exactly I needed to do that.  This means if you try passing the filename to some command it'll probably tell you "file not found" because it'll try to interpret the Eclipse project root as your file system's root.

It's *probably* safe to remove those `/` prefixes, I just wish I could remember why I added them...
