### ISSUE TITLE
Search for \$ doesn't work in reverse when on match

### ISSUE THREAD

**Issue by jayanderson** [vrapper/vrapper#605]
- Search for /\$
- Go forward through the matches with 'n' (I'm assume there are a few $ in the current document)
- When on a match attempt to go to a previous match with 'N'

I expected it to go to the previous match, but instead the caret doesn't move.

I've verified that this works for other searches (including 1 character searches). This also fails for '\(', '\*' and other characters which require escaping. Reverse matching also works with these characters when part of longer expressions (e.g. /\$1).

Vrapper version: 0.52.1

**Comment by keforbes** [comment]
Yep, I can reproduce this defect.  As a workaround, you can `:set noregexsearch`.  This will cause all search strings to be treated literally, not interpreted as regex.  I verified `N` will work after setting that property.

**Comment by keforbes** [comment]
Ok, I did a little more investigating.  It seems `N` is matching the current match under the cursor.  If you move the cursor one character to the left of the current match, `N` will jump to the correct previous match.  @albertdev, is it possible this defect was introduced with your fix for #539?

**Comment by albertdev** [comment]
@keforbes
I got a fix, but it is so simple that I don't know how previous versions got it right (maybe they didn't?). I'll see when I find time to verify it.

**Comment by albertdev** [comment]
It seems this has been broken ever since Vrapper was refactored in 2009. Searching backwards for a single character should now work.

Mind you, I still noticed some differences between Vim and Vrapper when searching for repeating substrings (e.g. search "aa" in "aaaaabaaaaaa" - Vrapper will sometimes move a single char whereas Vim moves two) and when searching backwards when the cursor is in the middle of a match (Vim moves back to start of match, Vrapper jumps back to a completely different match). I don't deem those real issues though, so if anybody objects they can open a new ticket.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150402) which includes this fix.  Go ahead and give it a try and let us know if you have any other problems.  Thanks!
