### ISSUE TITLE
Inherit shiftwidth to be the same as Eclipse's default Tab command

### ISSUE THREAD

**Issue by cirosantilli** [vrapper/vrapper#607]
By default, shiftwidth is 8, as used by the `<<` and `>>` commands.

But Eclipse uses 4 spaces by default for Java code indentation, which can be customized under Java > Code Style > Formatter , and this is the indentation that I want.

It would be cool then if Vrapper used the same width as the standard Eclipse Tab command (when text is selected selection) if shiftwidth is not set.

I would even consider removing shiftwidth and other related configurations as it seems to duplicate information contained elsewhere in Eclipse.

I have also noted that using `>>` indents with shiftwidth, while `Tab` uses the Eclipse value, which is kind of inconsistent.

**Comment by keforbes** [comment]
This has been mentioned before and, for better or worse, I'll describe my thoughts again.

I think in the vast majority of cases, people will set this value once and then forget it exists.  I think it's reasonable to just set Vrapper's settings to match Eclipse's settings and then never think about it again.  Right now, Eclipse doesn't know about Vrapper's settings and Vrapper doesn't know about Eclipse's settings.  It would be a lot of work for us to sync Vrapper's settings to Eclipse's and I don't think people change these settings often enough to make it worthwhile for us to automagically keep the two in sync.

As far as I see it, this is a minor annoyance and fixing it would require a lot of effort and knowledge of the Eclipse API on our part.  So I will happily mark this as a feature request but I don't feel compelled to fix it anytime soon.  I'd be happy to accept a Pull Request though.

Does that explanation make sense or do I just come off as being lazy?  I'm not saying it isn't worth doing, I just don't know the Eclipse API well enough to access (and possibly change) settings.  I don't think it would really benefit too many users either.

**Comment by keforbes** [comment]
I guess I should explain how I envision this feature if we were to do it.  I think Vrapper's settings should override Eclipse's.  The main reason for this is because we have the `autocmd` feature which allows you to set configuration values based on editor type.  You *could* for example set your `shiftwidth` to 2 in python editors, 4 in java editors, and 8 in xml editors.  It'd be nice if Vrapper automatically updated Eclipse's settings to match this `autocmd` value as you change editors.

Vrapper uses the `shiftwidth` value for the operations we control (like `>>` or `i_ctrl_t`) but Eclipse actually owns the `Tab` key and we can't intercept that button press.  That's why you see the behavior where `shiftwidth` is used in some scenarios but Eclipse's value is used in others.  So you really do have to keep the two values in sync; it's just a question of whether you do it yourself or if vrapper had the ability to keep them in sync for you.

**Comment by cirosantilli** [comment]
@keforbes you have already done so much to improve my day for free, that I wouldn't even imagine calling you lazy ;)

I apologize if this was already asked, feel free to close as a duplicate if you think appropriate.

I don't have much knowledge of Eclipse and if you say it's a complicated matter, I totally understand.

**Comment by albertdev** [comment]
As mentioned in #660 I've been working on this feature and made Vrapper detect the following settings for use as defaults:

* `tabstop`
* `shiftwidth` (most of the time equal to the tab width, though Java and CDT allow you to set it to a smaller value as well)
* `expandtab` (works OK except for the case where you use "mixed" mode, then it will default to true)
* `list`
* `number`
* `cursorline`

Again, the settings from Eclipse are only used if you don't set these values explicitly in your `.vrapperrc` file. Once you use `set` or `setlocal` the associated value will be used by Vrapper &mdash; Eclipse will keep on using its own settings.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.59.20150823) which includes this new behavior for anyone that wants to try it out.

**Comment by loonies** [comment]
@albertdev Is this detected per editor?

**Comment by albertdev** [comment]
@loonies 
The first three (`ts`, `sw` and `et`) are detected per editor and are not cached, this means that any changes you make to Eclipse settings will be immediately reflected in Vrapper.

Because Vrapper queries the current editor, project-specific settings are also picked up. I guess this seriously reduces the need for your "per-project vrapperrc" feature request in #594.

**Comment by loonies** [comment]
Sounds awesome. I'll give it a try. Thanks!
