### ISSUE TITLE
'O' doesn't work in visual block mode

### ISSUE THREAD

**Issue by keforbes** [vrapper/vrapper#613]
In visual mode and visual line mode, 'o' swaps the cursor back and forth between the beginning of the selection and the end of the selection.  In visual block mode, 'o' does nothing.

**Comment by keforbes** [comment]
This feature request comes from a comment on the Eclipse Marketplace:
https://marketplace.eclipse.org/content/vrapper

It looks like `BlockwiseVisualMode` needs a mapping for `o` to run `SwapSelectionSidesCommand` but I'm sure it won't be as simple as that.  We'll probably need some special handling for visual block mode.  I haven't confirmed this, I'm just assuming it won't be easy.

**Comment by albertdev** [comment]
Ah, I didn't know we had a comment section over there.

There are actually two mappings needed to be Vim-like: `o` switches the selection diagonally, `O` switches the selection vertically.

I have noticed this missing feature before. However, the current code is too complicated to my liking and it's also incomplete in some parts. For example, we don't draw a cursor and you can't grow the block selection to the left. I believe that code can use some serious refactoring, but I didn't feel up to it because I didn't want to potentially break existing users' workflow for a small gain.

All in all it should be doable, but I guess it takes some work.

**Comment by keforbes** [comment]
Ah, I didn't know the `O` feature existed. That does make a lot of sense for visual block mode.  Maybe @igrekster can help us out?

**Comment by igrekster** [comment]
@keforbes 
I can certainly have a look, but unlikely until the next week -- have a lot on my plate right now...

**Comment by albertdev** [comment]
I've been testing some fake caret painting code which simply draws a rectangle. It still needs lots of tweaking, but using this I noticed that our current block selection seemingly doesn't work with a right-to-left selection. Again, I think the block stuff is in need of a serious rewrite.

**Comment by igrekster** [comment]
@albertdev 
> I've been testing some fake caret painting code which simply draws a rectangle.

It would be handy to have it to at least debug the visual block mode, would you be able to share it?

> I noticed that our current block selection seemingly doesn't work with a right-to-left selection.

I've just tried it and didn't notice any problems, could you please elaborate on this one?

**Comment by albertdev** [comment]
@igrekster 
I did fix the UI in commit d2377ba18dec028ef0e1d7757a223d59491b19cd so that you can select backwards, but I can't recall what particular problem I was talking about. I really should have written it down...

As for the painting code, I'll look it up and create a pull request with the experimental code.

**Comment by albertdev** [comment]
@igrekster 
I found a few inconsistencies while testing again and created several issues for it (661 through 664). Some of them are UI related, but a few deal with how we use Eclipse's UI code to calculate blocks.

I believe that's why I previously called that mode incomplete: we delegate a lot of work to Eclipse and we don't handle all edge cases.
