### ISSUE TITLE
% doesn't jump to open/close location of multi line comment

### ISSUE THREAD

**Issue by sschaef** [vrapper/vrapper#623]
```
/*
 *
 */
```

Pressing `%` in vim when the cursor is on either `/*` or `*/` jumps to the other side respectively. In vrapper the error "no parentheses to jump found" is shown.

**Comment by keforbes** [comment]
I thought this was already filed elsewhere since I remember working on it awhile back.  I can't seem to find anything about it now so I'll just mark this as a feature request.

The difficulty is that we have some really nice generic code that handles any "pair" of matching characters (`( )`, `{ }`, `[ ]`, etc) but supporting a two-character pair (`/*` and `*/`) adds a lot of extra complexity.  If the cursor is on a `/` we have to see if the character before it is a `*` or if the character after it is a `*` and have the exact same logic for `*` looking for an adjacent `/`.  That type of check is a lot more complex than "is this character the matching pair".  I don't remember what caused me to give up on it a couple years ago when I was trying to get it to work.

Anyway, this is something that anyone could submit a Pull Request for.  All of the code would be in `ParenthesesMove.java` and you could create unit tests in `NormalModeTests.java` next to the existing `test_Percent` tests.  I'm sorry I don't really have time for this project anymore so it's unlikely I'll be able to do it myself.

**Comment by albertdev** [comment]
@keforbes 
You might have been thinking about [586: add comment text object](https://github.com/vrapper/vrapper/issues/586). If we would have that text object, the logic in `ParenthesesMove` is then limited to detecting that the cursor is on the start of a comment.
