### ISSUE TITLE
support \%V in command line search & replace

### ISSUE THREAD

**Issue by muellan** [vrapper/vrapper#637]
Since ```:s``` is a line oriented command VIM offers the ```\%V``` regex atom to restrict a search & replace to the visually selected area (say, two words in the middle of a line). 
So ```:'<,'>s/\%Va/b/g``` will replace all occurences of "a" with "b" in the visually selected area only.
Apparently Vrapper doesn't support this at the moment; maybe because it uses the Eclipse regex engine. Or is there any other way to restrict a search and replace to the selected area? (I mean other than with Eclipse's search&replace dialog, which I still use a lot)

**Comment by albertdev** [comment]
Sounds doable...

At any rate, I would only support it for Visual mode, using it in linewise is a no-op and blockwise might just be too complicated.

**Comment by muellan** [comment]
This would also open up a lot more possibilities for custom commands. Converting the word under the cursor to snake_case, camelCase or MixedCase suddenly becomes doable just with ```nmap``` and a bit of regex magic.

**Comment by muellan** [comment]
BTW I have no idea why VIM does't just support ``` `<,`> ``` for the exact visual range. Sure ```:s``` is only line oriented. But why not make an exception here and be consistent with the mark motions?

**Comment by albertdev** [comment]
Ex mode existed long before visual selections were a thing and always operated in line mode (plain "command mode" was actually called "visual" before because you are editing visually instead of through line-by-line commands). The marks are just there to specify which lines to operate on, and Bram Molenaar likely didn't want to break that assumption when he implemented `\V`.

You start talking about those special case things again, yet they seemed to work fine when I bound a key to the AnyEdit commands. Just create a fresh issue if you still can't get them to work and we'll try to sort it out. Make sure to add both the `eclipseaction` definition as well as the remaps when you do.

**Comment by muellan** [comment]
Oh I actually managed to make the AnyEdit command work - stupid mistake on my side. Nevertheless there are a few things you can't do with it (it only switches between lowerCamelCase and snake_case). If we had ```\%V``` one could do a lot of per-word or per-text-object changes right in the command line or the ```.vrapperrc``` that would otherwise only be possible with additional plugins.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.67.20160421) which includes this fix.  Please give it a try and let me know if it works for you.
