### ISSUE TITLE
:g problem when inserting new line

### ISSUE THREAD

**Issue by pa0los** [vrapper/vrapper#647]
There seems to be a problem with the :g command when executing it with "normal" operation generating a new line.

E.g.:
consider following file:
```
abc
123456
abc
def
123jvkdj
jkl
```
Let's isolate the lines containing "123" with a horizontal line "---". To do this we can execute following command:  `:%g/123/normal O---`
In GVIM this works as expected:
```
abc
---
123456
abc
def
---
123jvkdj
jkl
```
But Vrapper gives strange results:
```
abc
---
O---123456
abc
def
O---123jvkdj
jkl
```
This happens every time when I add a new line to the file (commands `o`, `j<cr>`). Seems like after first modification vrapper doesn't update the buffer when searching for the next occurrence.
Another issue is that after first modification vrapper doesn't return to 'normal' mode (as you can see by the `O` letter inserted), unless you explicitly do that with `<esc>` at the end of command. GVIM escapes to normal mode even without it.

**Comment by albertdev** [comment]
Indeed, I can reproduce this.

As you concluded, our `normal` command doesn't verify that it returns to Normal mode and sticks to Insert mode.. I'll see if we can check for this.

Also, is it possible that your example is wrong? I believe the first match did come out OK for me, though I'll go and check again later.

**Comment by pa0los** [comment]
Well, I believe that the result strongly depends on the example. With a different file / different search pattern I got even stranger outcome.

**Comment by albertdev** [comment]
I've been able to create another strange case when doing something like `g/---/normal O---` when ran on a file already containing triple-dashes. It will insert a number of triple-dashes all in the same spot because it will keep matching the original triple-dash when it got shifted one line down.

I haven't decided on a fix though... Either I do all searching up-front and somehow mark all matching lines so Vrapper can modify it in a second pass, or I need to mark the lines following the matched line and hope that the user hasn't blown that line away as well...

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.57.20150620) which includes @albertdev's work so far on this defect.  I'm not sure if it's "done" but it might be worth playing with this new version to see how it goes.
