### ISSUE TITLE
Make search to work with ':[/?]'

### ISSUE THREAD

**Issue by DoumanAsh** [vrapper/vrapper#665]
It seems that '/' is not recognized as command.
Usual /[pattern] works, but if you try :/[pattern] then Vrapper tries to execute the whole line as command

I know it is silly, but i often end up starting command and then switch to search... And it makes me sad sometimes :)

P.s. plugin is great.

**Comment by albertdev** [comment]
Oh wow, an `ex` fan!

Kidding aside, it looks like Vim accepts it and it doesn't look terribly hard to do. I'm going to mark this as a feature request until there's some time for somebody to look at this.

**Comment by keforbes** [comment]
Finally got time time to do this.  At first I thought it was as simple as redirecting `:/` to `/` but it turns out in Vim `:/` moves the cursor to the beginning of the line (first non-whitespace character) of the first match.  Yet if you do `n` or `N` it jumps directly to the previous/next match, not the line of the match.  Weird behavior, but simple enough to emulate.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.67.20160414) which includes this fix.  I know it's almost been a year since you requested this feature but if you could test it out and verify it behaves the way you expect I'd appreciate it.  Thanks!

**Comment by DoumanAsh** [comment]
Glad to hear! Even though i didn't use Eclipse in a while now i'll try to take a look as soon as i'll have an opportunity
