### ISSUE TITLE
Regex problem with umlauts

### ISSUE THREAD

**Issue by cbertoldi** [vrapper/vrapper#675]
Sample text

    ;xx;AAAA
    ;xx;aaaß
    ;xx;aaaÜ

used regex `'<,'>s/;(\w*)$/;\1;\1/`

expected:

    ;xx;AAAA;AAAA
    ;xx;aaaß;aaaß
    ;xx;aaaÜ;aaaÜ

got instead:

    ;xx;AAAA;AAAA
    ;xx;aaaß
    ;xx;aaaÜ

It looks like that **umlauts, ß** and maybe other characters, are not considered as word characters.
It could be somehow similar to issue #543.

**Comment by albertdev** [comment]
Sorry for waiting so long to get back to you, I can reproduce this and hence will mark it as a defect.

**Comment by albertdev** [comment]
On second thought, it looks like Vim has the same problem:
http://unix.stackexchange.com/q/60481/70874

Vim *does* offer `\k` though, which is a shorthand for whatever you have set as `'iskeyword'`. I'm changing this from a defect to a feature request for the `\k` character class.

**Comment by keforbes** [comment]
Sorry to poke an old issue, but I was looking at this and found something.  Our regex is already just the Eclipse/Java regex engine so we don't have to rely on Vim's behavior here.
http://download.eclipse.org/modeling/emf/emf/javadoc/2.4.2/org/eclipse/emf/ecore/xml/type/internal/RegEx.RegularExpression.html
and
http://stackoverflow.com/a/10894689

It looks like we should be able to add the `u` or `Pattern.UNICODE_CHARACTER_CLASS` flag to include unicode characters in the "word" regex class.  I wonder if it would hurt to have unicode mode always enabled or if it would be best to just add support for the `u` flag.  I haven't actually tried implementing either one, but it looks promising.

**Comment by keforbes** [comment]
My idea for using `u` or `Pattern.UNICODE_CHARACTER_CLASS` didn't pan out.  Eclipse's search function doesn't support them.  I could only use them if I was creating a `Pattern` object.

However, I *was* able to implement `\k` in a regex search like @albertdev mentioned.  This makes us more Vim-compliant anyway since Vim doesn't handle umlauts by default either.  So this would be the same recommended solution in Vim too.

If I change your sample regex from:
```
'<,'>s/;(\w*)$/;\1;\1/
```
to:
```
'<,'>s/;(\k*)$/;\1;\1/
```
then I get the expected behavior.  Fortunately, our default `iskeyword` value already includes `\u00C0-\u017F` so umlauts are included without modifying the default value.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.67.20160426) which includes this fix.  Please give it a try and let me know if it works for you.  Thanks!
