### ISSUE TITLE
Exit Insert mode on buffer save (Ctrl+S)

### ISSUE THREAD

**Issue by saamalik** [vrapper/vrapper#688]
Hi All,
Not a bug, more of a question: How do I cause "Ctrl+S" (Save) operation cause the buffer to leave insert mode and go into the normal mode? 

Thanks,
Saad

**Comment by keforbes** [comment]
I think the only way you could do that would be to define a new Vrapper mapping for `Ctrl-S`.  You could add the following to your `.vrapperrc`:
```
imap <c-s> <esc>:w<cr>
```
That would exit Insert Mode and save the file.  Of course, in order to do that, you'd have to unbind `Ctrl-S` (Save) from Eclipse.  Vrapper only receives keystrokes if Eclipse doesn't have anything set for them.  So I'd also add this to your `.vrapperrc` to save in Normal Mode too:
```
nmap <c-s> :w<cr>
```

**Comment by keforbes** [comment]
This isn't a bug, it was just a question on how to do something.  I answered it as best I could but I don't think there's any code change pending here.

**Comment by albertdev** [comment]
@keforbes That's why I applied the "Other Feedback" label.
Maybe we should be more explicitly asking the "topic" starter to close the ticket if it solves their problem?

**Comment by saad-cliqr** [comment]
Thanks @keforbes solved it for me.
