### ISSUE TITLE
== does not indent the current line

### ISSUE THREAD

**Issue by xuhdev** [vrapper/vrapper#696]
`==` seems not indenting the current line on my system.

To reproduce, open a source file and arbitrarily mess up some indent. Move the cursor to a messed line and run `==`, but nothing happens.

I'm on Mars on Debian.

**Comment by keforbes** [comment]
The `==` command is specific to the programming language it's used in so you have to install one of our optional language-specific plugins to get that behavior.  We currently only support `==` in Java (JDT), C/C++ (CDT), and Python (PyDev) via these plugins.  This is because we're actually calling the "auto-indent" Eclipse command provided by each of those tools rather than implementing it ourselves.

http://vrapper.sourceforge.net/documentation/?topic=optional_plugins#cjavapy

**Comment by xuhdev** [comment]
@keforbes Can you kindly show me where to install the extensions? I cannot find it on Eclipse MarketPlace or the website.

**Comment by xuhdev** [comment]
Ah, I found it in the update site. Thanks!
