### ISSUE TITLE
Insert Mode overwrites following characters

### ISSUE THREAD

**Issue by jarmoni** [vrapper/vrapper#723]
When switching to insert mode by pressing *i, I, a, A* the cursor starts at the correct position but instead of inserting, it overwrites the following chars. Means: An *i* behaves like an *R*.

The  problem occures most of the time independent of file-type (java, xml,...). It seems that everything is fine when opening a new file, but after a while insert-mode stops working. 

I am using:
Version: Mars Release (4.5.0)
Build id: 20150621-1200

**Comment by albertdev** [comment]
If you check your statusbar then you'll find the Vrapper mode, a field indicating whether the current file is "Writable" or "Read-Only" and then Eclipse's insert/replace status. Please keep an eye on that third field: Eclipse should normally show "Insert" or "Smart Insert" while Vrapper is in insert mode while it should read "Overwrite".

Is it possible you use the `<Insert>` key a lot?

**Comment by jarmoni** [comment]
Tried to reproduce issue on different machines.
Could not.
Re-installed Plugin - fine so far :+1:

**Comment by albertdev** [comment]
I could reproduce the following scenario:

* Check that the `<Insert>` key is still bound to "Toggle Overwrite" in the Eclipse Preferences > Keys page (this is an Eclipse default).
* Press `<Insert>`. Notice that the status bar changes a field to `Overwrite`.
* Press `I` to switch Vrapper's mode to `-- INSERT --`. Notice that the status bar still says `Overwrite`.
* Enter something and notice that the characters already on the line are overwritten.

I made a fix so that Vrapper will explicitly disable Eclipse's `Overwrite` mode when switchin to `-- INSERT --` mode.
