### ISSUE TITLE
g and Ctrl+g different as in vim.

### ISSUE THREAD

**Issue by lewicki-pk** [vrapper/vrapper#724]
Hello,
First of all: good job with this plugin. I love using it.
Unfortunately one of my favourite functionalities is missing:
When I select couple of lines in vim (in visual mode) and press "g" and then "ctrl+g" I receive information about lines, words and characters that are selected (just as below), but when I do the same in vrapper I only get some different information (also below).
Is this a bug? I used this in vim to check how many lines I have selected. Is there a way to count lines in vrapper?

Vim "g" and "ctrl+g" result:
Selected 3 of 7 Lines; 3 of 5 Words; 15 of 33 Bytes
Vrapper "g" and "ctrl+g" result:
Position M 305/ 305 V; line 18/ 18 view line; horizontal offset 149

Thanks,
Piotr

**Comment by keforbes** [comment]
It looks like our implementation is only looking at the current cursor position.  I don't think it's taking visual mode into account.  This should be something we can add.

**Comment by albertdev** [comment]
> Is this a bug?

Mostly *no*. Nobody ever asked about `g CTRL-G` before so we never implemented it.

It's just that I needed some tool to quickly print the current location for debugging. I chose to bind it to `g CTRL-G` because it isn't *too* easy to find out accidentally except for those who expect it to be the real thing.

So yeah, it's simply waiting to be implemented.

**Comment by lewicki-pk** [comment]
If so, I would be pleased if any of vrapper dev's could implement this.
Thanks :-D

**Comment by albertdev** [comment]
@solde9 was so kind to provide a pull request with a fix. This change will be included in the next release build and likely the next unstable build after that.
