### ISSUE TITLE
Normal command in line mode

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#728]
The 'normal' command in line mode is really nice. For instance, you can select a range of lines visually, and then hit: ':normal A;'. This will append a semi-colon to the end of every line, and it's a lot more intuitive (for me) then doing this with /s. vrapper has a couple of issues with this. First, I just updated from version 55 to the latest, and I have found that the example I gave no longer works at all. Any normal mode command that involves entering insert mode and entering text no longer works. However, selecting a range and hitting ':normal dd' still works (and deletes all the lines as expected). However, there's also a second issue: undo treats this indeed as one command per line, instead of as a single command (like Vim does).

**Comment by quicknir** [comment]
Note that a workaround that works perfectly seems to be first recording your command to a macro, and then simply doing ':normal @@' or what not. Works and even undo happens all in one step!

**Comment by albertdev** [comment]
It sounds very odd that your macro workaround works that different compared to undo. I would have expected that it would still work line by line.

**Comment by quicknir** [comment]
Yeah I agree, very odd, but the fact that it works with a macro perhaps means there's hope that it won't be so bad! Let me know whether you are able to reproduce.

**Comment by albertdev** [comment]
I can reproduce the undo problem in the latest release version (0.64.0) and marked it as "Annoyance".

You are correct though that the current unstable version (0.65.20160215) actually has a broken `:normal` command as I can reproduce the insert mode problem when building from source.

I've since tracked down the source of the problem and pushed a fix because this is such low-hanging fruit. This fix will be included in the next release and unstable build.
