### ISSUE TITLE
broken caret geometry while using non fixed-width font

### ISSUE THREAD

**Issue by yegor-alexeyev** [vrapper/vrapper#743]
There are 2 issues with caret.
1. Caret width does not match underlying character width
2. Caret does not slope under an italic character

This issues make positioning difficult(especially positioning under narrow characters like braces or punctuaton symbols)

**Comment by albertdev** [comment]
What kind of editor are you using? (File type, what kind of plugins you installed to edit it, possibly Eclipse version...)

Do you have a screenshot of what it looks like with italics, with and without Vrapper enabled?

In short though, Vrapper currently doesn't support variable width fonts because Vim doesn't either and because it would take a slight bit of extra work to recalculate the caret width, instead it uses average char width.

The fact that Vim cannot use variable width fonts puts us on thin ice though because we need to figure out from scratch how the editor should behave. Should moving up/down stay in the same "display" column or should it stick to the *x*th character on the line? Should the "block" caret change width all the time and should it really be a sloped box when it tries to wrap over an italic character?

All of these questions make me reluctant to accept this as an issue or feature request. I guess this shows how old Vim is...

**Comment by albertdev** [comment]
Oh, and before I forget: how do you handle tabs and tabstops?

**Comment by yegor-alexeyev** [comment]
![broken-caret](https://cloud.githubusercontent.com/assets/2978978/15355359/ce3b49bc-1cfa-11e6-9c2c-a92b51f70e6b.jpg)

**Comment by yegor-alexeyev** [comment]
>> Should moving up/down stay in the same "display" column or should it stick to the xth character on the line?
This is already works good. The cursor tryes to stay in the same "display" column.
I am in MS Windows 10, using Eclipse Mars.

**Comment by yegor-alexeyev** [comment]
>>Should the "block" caret change width all the time and should it really be a sloped box when it tries to wrap over an italic character?

MS Word behaves this way(the caret becomes slopped)

**Comment by yegor-alexeyev** [comment]
Anyway, I looked the code and it seems to me that the required changes are not very difficult. So I can make my own fork for my own use. 

P.S. Tabstops are not a problem because they happen to be mostly first characters of the line.
