### ISSUE TITLE
Please add LICENSE file to the repository

### ISSUE THREAD

**Issue by vovagrechka** [vrapper/vrapper#745]
MIT or something. Otherwise it seems I'm not allowed to copy-paste any code from Vrapper into my software, which I would like to do :)

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by albertdev** [comment]
It's a good idea to add that file, though I'm afraid Vrapper has been using GPL v3 all along as shown [on the SourceForge project page](https://sourceforge.net/projects/vrapper/) or in [the Eclipse install files](https://github.com/vrapper/vrapper/blob/master/vrapper-stable-feature/feature.xml). I've heard from the current project maintainer that there was a case of someone making a commercial closed-source derivative of the originally permissive Vrapper sources, which is why the authors released the next version under the GPL.

A LICENSE text which clearly indicates GPL v3 would have saved you time I guess, but what do you need it for? If you're using Eclipse then Vrapper should integrate with any Eclipse editor based on the `AbstractTextEditor` class.

If you need it for something else I could explain some of the architecture for you, or you could look at [the JavaVi code](https://sourceforge.net/projects/jvi/) which is MPL v1.1. If you still want to use Vrapper you could use the built jar files, so explaining what you want to do may still be interesting.

**Comment by keforbes** [comment]
Vrapper has always been GPL.  That's the license you accept when installing it and has been attached to the project the whole time.

As @albertdev mentioned, we had a case in the past where someone re-branded vrapper to their own name and logo and tried selling it under a closed source license.  We contacted gpl-violations to stop that person.

I'm sorry we didn't have a license.md file but that's only because we migrated from sourceforge to github and sourceforge clearly states that it is GPL.

I'm sorry, but if you want to stick some vrapper code in your closed source project then I don't think we can help you.

**Comment by keforbes** [comment]
I'm closing this issue.  @albertdev has added a License.md file to the project explicitly stating it is GPL.

**Comment by keforbes** [comment]
Sorry, I didn't mean to sound dismissive with my comments.  If you want to take vrapper code and insert it into your closed source project then we can't help you.  However, if you want to include vrapper (unmodified) in your project then I think that is allowed under GPLv3 since it would be treated as a library.  It all depends on what you want to do with it.

**Comment by vovagrechka** [comment]
To be short, I want to tweak Vrapper to be more "hackable and dynamic." One example of Vrapper's restrictions I've encountered so far is inability to add new :command without the need to restart debugged IDE with my extension. UnionStateProvider prevents me from doing this because it caches all commands contributed by extensions. So, what I want is the same Vrapper but with MyStateProvider instead of UnionStateProvider, and with following line modified accordingly: https://github.com/vrapper/vrapper/blob/master/net.sourceforge.vrapper.eclipse/src/net/sourceforge/vrapper/eclipse/platform/EclipsePlatform.java#L231.

My project is not closed source. And actually I'm OK with making it GPL instead of MIT. Now that you've added LICENSE.md file, I'll just include it in my project along with reference to original Vrapper. Thanks.

**Comment by albertdev** [comment]
Are you thinking of using more OSGi infrastructure rather than the Eclipse extension registry or something?

Mind you, the thing is that it's not dynamic right now due to a) Eclipse extension being (immutable) singletons and b) caching per editor type.

**Comment by keforbes** [comment]
@vovagrechka, if there are changes you want in vrapper to make it more hackable and dynamic, feel free to submit a Pull Request and we'll get it into vrapper itself.  Of course, keep @albertdev's restrictions in mind in case those changes aren't possible. :smile:

**Comment by vovagrechka** [comment]
@albertdev Currently simple URLClassLoader seems to be sufficient for me. My extension is split into two parts, "static" and "dynamic". Static part declares 1) a bunch of required bundles in MANIFEST.MF that dynamic part might need on classpath, and 2) necessary extensions (both to Vrapper's points and core Eclipse ones). Then implementation of getCommands(), for example, is something like:

public EvaluatorMapping getCommands() {
    ....
    if (loader != null) {
        loader.close();
    }

    loader = new URLClassLoader(new URL[] {new URL("file:///path-to-my-dynamic-part/classes/")},
                                getClass().getClassLoader());
    Class<?> implClass = (Class<?>)loader.loadClass("myextension.MyStateProviderDynamicImpl");
    MyStateProviderDynamic impl = (MyStateProviderDynamic)implClass.newInstance();
    return impl.getCommands();
}

Because specified parent class loader is the one that loaded extension itself, dynamic part has access to all necessary Eclipse stuff. This way I don't even need to have two Eclipses opened all the time. I just save/compile a Java file in dynamic-part project and see changes applied to running Eclipse instance immediately. This is also better than modifying code under debugged Eclipse instance, as I can do any kind of changes (new classes, methods, etc.) and have everything reloaded without restarting JVM.

In future I will have implementation of dynamic part mostly in JavaScript (used through Nashorn) and eliminate Java altogether :)
