### ISSUE TITLE
expandtab isn't working

### ISSUE THREAD

**Issue by aholub** [vrapper/vrapper#754]
expandtab doesn't seem to work at all in 0.68.1 (under Neon). Tried setting it both from .vrapperrc and by typing set

**Comment by albertdev** [comment]
Can you give an example? What operation are you executing to test it with, e.g. `==` or `>>`?

Please keep in mind that just pressing `<Tab>` will always use the Eclipse editor settings, and Vrapper will try to adjust to that when you don't explicitly set `expandtab`.

**Comment by aholub** [comment]
I'm just typing. I hit "i" to enter insert mode, then type:

<tab>x<tab>x<tab>x

tabs seem to be  inserted, not spaces. In vim, at least, all tabs on the line are expanded as I type when expandtab is set. I do have the eclipse editor set to replace tabs with spaces, so I'd expect to see spaces everywhere.

**Comment by albertdev** [comment]
Again, pressing `<Tab>` is always plain Eclipse functionality. Vrapper settings **will not** affect it, and the automatic adjustment means Vrapper will take whatever pressing `<Tab>` produces.

If you still keep seeing tabs then you have failed to change the right preference as [Eclipse has many different settings for tabs vs. spaces, all dependant on the type of editor (see stackOverflow)](http://stackoverflow.com/a/408449/983949).

It is due to this multitude of preferences that we chose to never override them (if we even could).

**Comment by albertdev** [comment]
@aholub 
Did you try changing those formatter settings I mentioned? Did that help with your problem?

Until there is more feedback I'm going to label this issue as "Unconfirmed".

**Comment by aholub** [comment]
@albertdev I did try them and they worked as far as they went. I really need full tab expansion, though, and none of the Eclipse vi plugins seem to do that, so I've moved to a different IDE entirely for this project. Thanks.
