### ISSUE TITLE
Global marks stop working

### ISSUE THREAD

**Issue by geg-mopo3** [vrapper/vrapper#766]
Global marks stop working sometimes. The reason is not mistyping as I only use VIM in Linux as editor and it doesn't happen.

**Comment by albertdev** [comment]
Are there any errors in the Eclipse log file?
Do you happen to frequently clear all bookmarks (which Vrapper uses to store global marks)?

**Comment by geg-mopo3** [comment]
Yes, there are some exceptions in the log files as usual, but I don't know whether they relate to this problem. I've never cleared the bookmarks in Eclipse, don't even know how to do this.

I've also noticed that if I execute `:marks` it doesn't show me all the defined global marks (only if the related file is open?). VIM shows all defined global marks no matter whether the files are loaded or not.

**Comment by albertdev** [comment]
Hmmm, if `:marks` doesn't find them then that might explain why you couldn't move to it.

What version of Eclipse and Vrapper are you using?

**Comment by geg-mopo3** [comment]
Eclipse for RCP and RAP Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

Vrapper 0.70.0

**Comment by albertdev** [comment]
@geg-mopo3 No idea if you're still using Vrapper or Eclipse, but know that I found the problem: the code wouldn't work if the target editor was not opened or part of the same project as the current file. Since you are likely using multiple projects (especially when e.g. using Maven), this would have caused the problem.

The `:marks` command on the other hand was always wrong if the target editor was not open, so I fixed that as well.

The fix will be part of the next release.
