### ISSUE TITLE
Feature Request - SHIFT-K

### ISSUE THREAD

**Issue by gajatko** [vrapper/vrapper#770]
It seems that SHIFT-K does nothing as for now. It could display docs, like in a similar plugin for intelliJ.

**Comment by albertdev** [comment]
For future reference, here's the corresponding Vim feature in the Vim-docs: http://vimdoc.sourceforge.net/htmldoc/various.html#K

It all depends on whether Eclipse exposes an easy-to-use set of helpers. If so, we can simply call them whenever you press `K`.

I feel it would be language-specific though and hence not supported in just any editor. What kind of editors are you using now?

**Comment by gajatko** [comment]
Currently Java. In my keyboard layout, docs popup is binded to F2 key, so it's fine. But anyway, support for `K` would be nice.

**Comment by igrekster** [comment]
If there is a shortcut for it in Eclipse you could map it to that commad:
```
au "Dart Editor" eclipseuiaction! doc com.google.dart.tools.ui.edit.text.dart.open.external.dartdoc
au "Dart Editor" nnoremap K :doc<CR>
```

**Comment by gajatko** [comment]
And this should go to the "_vrapperrc" file on Windows, right? Sorry for noobie problems, but I couldn't find it. Should I create it in "C:\Users\[username]"?

**Comment by keforbes** [comment]
@gajatko, I was just looking at this feature request.  In Eclipse, I see `F2` bound to "Show tooltip description" and `Shift+F2` bound to "Open Attached Javadoc".  "Open Attached Javadoc" is a Java operation which opens the javadoc in a new editor tab.  "Show Tooltip Description" is a generic Eclipse operation which popups the same tooltip that would appear if you moused-over the item.  Which of these operations would you prefer?

For reference, "Open Attached Javadoc" is:
`org.eclipse.jdt.ui.edit.text.java.open.external.javadoc`
and "Show Tooltip Description" is:
`org.eclipse.ui.edit.text.showInformation`

And yes, you would add @igrekster's example `eclipseuiaction` to `_vrapperrc` in `C:\Users\[username]`.  Depending on which behavior you want, it would either look like this:
```
au "Java Editor" eclipseuiaction doc org.eclipse.jdt.ui.edit.text.java.open.external.javadoc
au "Java Editor" nnoremap K :doc<cr>
```
or this:
```
au "Java Editor" eclipseuiaction doc org.eclipse.ui.edit.text.showInformation
au "Java Editor" nnoremap K :doc<cr>
```

I tested both of those scenarios and they both work fine.  I'm going to close this issue because neither choice is equivalent to what Vim would do.  It's up to the user to decide what they want to happen when they hit `K` so I'll leave this as a user customization rather than implementing either of those behaviors.
