### ISSUE TITLE
Newline replacement not working for :g/<pattern>/s

### ISSUE THREAD

**Issue by fvalves** [vrapper/vrapper#774]
Hello,

for Vrapper version 0.70.0, when running command `:g/<pattern>/s`, neither "\r" nor "\n" in the replace string are being interpreted as the expected newline or carriage return respectively, as they do on command `:s/foo/bar/`. "\n" is inserted literally, while "\r" is curiously converted to "\R".

**Comment by keforbes** [comment]
From our docs:
> In the replace string, \r will be interpreted as a (platform-independent) newline. Using \n in the replace string will result in the carriage return (0x0D) character being inserted literally. This means it may work fine on files with Unix line endings but if you have Windows line endings \n will cause problems. 

Can you give me an example of a replace where `\r` is being mapped to `\R`?

**Comment by fvalves** [comment]
The behavior described in the documentation works correctly for the :s/foo/bar/ command, yes.

The problem occurs only when using the :g/pattern/s/find/replace/ command.

Right now I cannot send an image, only on Monday will I be able to do it. But a simple :g/.*/s/^/\r/ should cause the issue.

**Comment by keforbes** [comment]
I finally had a chance to test this out.  It looks like the problem only occurs when you put either `^` or`$` in the search text.  Searching for actual characters correctly replaces it with a newline.  The same is true with `:s/^/\r/`, not just `:g`.

I believe the problem is that we have a special case for `^` and `$` where we just insert the text (since no text is being replaced) rather than performing the substitution operation, which would interpret `\R` as a newline.  For whatever reason, Eclipse's regex engine interprets `\R` as a newline so vrapper replaces the expected vim format `\r` with Eclipse's `\R`.  Unfortunately, we're replacing `\r` with `\R` and then inserting the text literally rather than treating it as a regex.
