### ISSUE TITLE
Support for alternative keys to escape (eg. jk)

### ISSUE THREAD

**Issue by rNoz** [vrapper/vrapper#781]
As seen here [http://vim.wikia.com/wiki/Avoid_the_escape_key](http://vim.wikia.com/wiki/Avoid_the_escape_key), some people (like me) use vim and/or spacemacs (evil mode) with alternative keys to escape.

Is there any plan to integrate this functionality? Will it be difficult?

In my case I use `jk` (with a configurable timeout) to escape, so if you press `jk` really fast (as fast as the timeout is specified) it does the same as `<Esc>`. In the above guide they set this up: `:imap jk <Esc>`

**Comment by keforbes** [comment]
Yep, I use `imap jk <esc>` too.

Vrapper uses `.vrapperrc` for anything you would set in `.vimrc`, though we don't support everything `.vimrc` can do.  If you have a simple `.vimrc` you can just put `source .vimrc` in your `.vrapperrc`, otherwise you should enter the specific commands we support.

Here are all the settings Vrapper supports:
http://vrapper.sourceforge.net/documentation/?topic=configuration

**Comment by keforbes** [comment]
Also, note that we don't support the `timeout` setting (#741) so Vrapper will wait indefinitely for a mapping to be completed (or not completed).

**Comment by rNoz** [comment]
Thanks! I see that it works. At least the basic mode, but I can see that if I write `j` and some time later `k` it triggers the same `Esc`, but I can live with that, I think it is not so common `jk` in a word.

I laughed with what you said in #741.

**Comment by albertdev** [comment]
@rNoz Is there still something unclear or did we sufficiently help you to get started using Vrapper?

**Comment by khaledbenz** [comment]
Please help me I can't find the  vrapperrc file which is supposed to be located in the HOME directory which i cant' find

**Comment by keforbes** [comment]
> Please help me I can't find the vrapperrc file which is supposed to be located in the HOME directory which i cant' find

The file doesn't exist by default, you have to create it.  If you're on Linux, just create `.vrapperrc` in your HOME directory (`/home/<username>/`).  If you're on windows, it's easier to create `_vrapperrc` since windows doesn't like files that start with `.` (create it in `C:\Users\<username>\`).  Or, you can edit eclipse's ini file and set a custom location with `-Dvrapper.vrapperrc=<filename>`.
