### ISSUE TITLE
Focus lost when typing '/' or ':' in a newly opened editor

### ISSUE THREAD

**Issue by jeroen-dhollander** [vrapper/vrapper#813]
**Description:**

If you open a new file, the first time you press '/' or ':' it most often does not display the floating input bar.
Instead, the focus is completely lost (no eclipse shortcuts work anymore).
The only solution is then to click with the mouse anywhere in the editor.
After that typing '/' will show the previous input as well (so if you typed '/abc', then clicked the mouse and press '/' it will show the input bar containing '/abc').

**Platform & more information:**
   - Linux (CentOS 7).
   -  Eclipse versions: Fails on Oxygen/Photon, works on Neon.
   -  File types: any (I've had it on .txt, .c/h/cc, on .py).

   * I've tried for the longest time to figure out the exact steps to reproduce,
but I can't figure out when it triggers or not.
I would say 90% of the times I open a file I open have this issue.
   * Note it was also mentioned by Yongho-John-N in https://github.com/vrapper/vrapper/issues/811 (see his second post).
   * Nothing displays in the Error Log

Sorry for the lack of concrete information, if there is anything I can do to get something more,
please let me know.

Thanks,

Jeroen

**Comment by keforbes** [comment]
Huh, that's odd.  You're right, if I double click on a file in the Package Explorer I can immediately use `j`/`k` to move all around the file but if i enter command-line mode with `/` or `:` it just loses focus on the editor.  But then using the mouse to put the focus back on the editor fixes everything.

**Comment by Yongho-John-Nam** [comment]
similar symptom

```:vs open_file ```
or multiple editor
```:q ```

loses focus too.

**Comment by albertdev** [comment]
@Yongho-John-Nam Thank you for feedback.
However, please keep issues on-topic because that looks to be already tracked in #435.

You're welcome to report anything new in that ticket, though as you can read there it looks like it's more to do with how Eclipse handles things than with Vrapper. I dread to implement workarounds for Eclipse problems because they have the potential for doing more bad than good (if they work at all).

**Comment by Droj** [comment]
A tad additional info, hoping it will help. :) This is a deal-breaker on Oxygen.

Running 0.72 on Eclipse Neon GTK3, I'm observing the 1st part of this behavior: typing '/' or ':' in a new editor will often not _display_ the command line. However, typing one more character will cause it to show up and all it good, so not really a big deal.

In Oxygen, the command line does not show up, and focus is completely lost in a way similar to #435.

**Comment by konradsa** [comment]
I got the same issue under Oxygen, often after opening a file commands won't work and focus is lost. I am running under Linux GTK3 as well. I see usually an error in the error log when this happens.

![eclipse-error](https://user-images.githubusercontent.com/8036995/47356438-12931b00-d692-11e8-867e-3b1c464b8dcb.png)

**Comment by albertdev** [comment]
@konradsa Revisiting this issue I see you posted that image of a stacktrace. I believe the root cause was covered by #812, and the latest build on the "Unstable" update site should include the fix now.

I can confirm I saw this issue on a Windows Subsystem for Linux install though...

**Comment by albertdev** [comment]
This issue was definitely annoying by happening only 5-10% of the time...

Turns out that sometimes the commandline widget would be opened with a size of 0 pixels wide by 0 pixels high, enough to initially steal the focus but obviously not to paint anything or receive keypresses. The reason for that invalid size seems to be that GTK tries to save calls to a paintlistener which Vrapper registered, meant to sync the commandline size with the parent editor. On Windows there seems to be no such issue.

Meanwhile GTK seems to also spam the `stderr` stream with this:
```
(Eclipse:1307): Gtk-CRITICAL **: 17:22:57.532: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```
This appears to be a problem in SWT-GTK or GTK3 in general.

Anyway, this fix didn't make it into the Vrapper 0.74 release. We'll see when 0.75 (unstable) or 0.76 gets released, maybe I have some time during the upcoming months to fix more stuff.

**Comment by jeroen-dhollander** [comment]
Thanks for fixing this, I'm eagerly awaiting the (unstable or stable) release of 0.75 now :)

In the mean time, I might try to compile the latest version locally.
I'll let you know if that exposes any new issues related to this fix.

Thanks!

Jeroen

**Comment by keforbes** [comment]
@jeroen-dhollander, I hope you didn't spend too much time trying to compile the latest version locally.  I've updated the unstable update site with a new build (0.75.20181126) which includes @albertdev's latest fix.  Please let us know if it works for you!

**Comment by keforbes** [comment]
@Droj, not sure if you saw my last comment but please test out the latest unstable build and let us know if it resolves the problem for you.  Thanks!

**Comment by jeroen-dhollander** [comment]
I had not spent any time on this yet, I was planning to do this this evening.

I tried the 0.75 unstable build and it now works.

Thanks for the awesome support!

Jeroen

**Comment by konradsa** [comment]
Awesome!

@keforbes whenever you can create a release zip it will be able to test it out as well, can’t access sourceforge.

**Comment by keforbes** [comment]
@konradsa, sorry you can't access sourceforge.  We actually have a backup update site hosted on github for users like yourself.  Thanks for reminding me to update it. :smile:   I don't always update the unstable update site on this backup since it requires committing binary files but I just pushed the most recent unstable build to it so you can test out the fix for this issue.

Please try adding this update site to your eclipse to update vrapper to version 0.75.20181126.
https://vrapper.github.io/update-site/vrapper-unstable/

**Comment by konradsa** [comment]
@keforbes Can we have a minor release zip for this important fix please? I can’t access sourceforge update site, my company firewall blocks it. This issue is driving me crazy and I would have to wait two more months to get this fix otherwise. Thanks, you guys rock!

**Comment by konradsa** [comment]
@keforbes you guys rock, thanks so much!

**Comment by Droj** [comment]
@keforbes, unfortunately, my firewalling situation is even worse. I do not have direct access to the internet, so I would only be able to verify if you could create an update site as a ZIP file.

**Comment by albertdev** [comment]
@Droj If you go to https://github.com/vrapper/vrapper.github.io you see the Git repo associated with out Github site. If you click the green "Download or clone" button you can download a zip with all of the update site's files. You can then add a local directory as an update site.

**Comment by keforbes** [comment]
@Droj, or you can just download the zip of the release here:
https://github.com/vrapper/vrapper/releases/download/0.74.0/vrapper_0.74.0_20181124.zip

And install it manually.  The zip file has a README.txt for installing it.  You *should* be able to just add the zip file itself as an "archive" update site in Eclipse.  Or, you can manually drop the files into the right directories.  The README.txt has directions for both

**Comment by keforbes** [comment]
> So, I still see the problem with vrapper_0.74.0_20181124.zip. But that's still 0.74... are you expecting it to be resolved there too?

No, sorry, forgot this fix didn't make it into the stable release.

> I was able to get the update site for 0.**75**.20181126 by downloading the repo (thanks for that tip). It appears to be working properly with that version on Oxygen.

Great news!  Glad to hear it!
