### ISSUE TITLE
Can't bind eclipseaction to Go to Next/Previous annotation

### ISSUE THREAD

**Issue by spiralsam** [vrapper/vrapper#816]
This id pair for this at first appears to be [GOTO_NEXT_ANNOTATION / GOTO_PREVIOUS_ANNOTATION](https://help.eclipse.org/kepler/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/ui/texteditor/ITextEditorActionDefinitionIds.html#GOTO_NEXT_ANNOTATION)

```
eclipseaction vrapprev org.eclipse.ui.edit.text.gotoPreviousAnnotation
eclipseaction vrapnext org.eclipse.ui.edit.text.gotoNextAnnotation
```
But executing them does nothing. Then there's [IWorkbenchCommandConstants NEXT/PREVIOUS](https://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/ui/IWorkbenchCommandConstants.html#NAVIGATE_NEXT) or [ActionFactory NEXT/PREVIOUS](https://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/ui/actions/ActionFactory.html#NEXT)

```
eclipseaction vrapprev org.eclipse.ui.navigate.previous
eclipseaction vrapnext org.eclipse.ui.navigate.next
```
Executing vrapprev actually does seem to do nearly what it's supposed to (jumping to the error) though without selecting the text causing the error, and instead deforms the cursor to an underline bock for some reason. But executing vrapnext doesn't work well. It jumps to the next error only once; executing it multiple times in succession will not move past the error text that is currently at the text cursor, as will happen when executing vrapprev (or when executing Navigate->Next/Previous Annotation multiple times manually).

**Comment by keforbes** [comment]
Ok, it took me a while to find this again (reaching back into memory) but this is exactly the usecase intended in #762.  The basic issue is that `eclipseaction` explicitly clears any selection after the operation runs.  Also, after the first match, ":vrapnext" was always matching on the exact same position you were on; if you moved one character to the right then ran `:vrapnext` again it would work.  This is because it was lacking the state to realize it had already matched on the item under the cursor.  I don't know how to set an `Annotation` in Eclipse so I wasn't able to test that behavior.

Anyway, back to #762.  I was able to get your desired behavior with the following commands:
```
noremap \w <Plug>(eclipse-textobj:org.eclipse.ui.navigate.next)
noremap \b <Plug>(eclipse-textobj:org.eclipse.ui.navigate.previous)
```
Note that using `\` (leader) isn't actually required for your mapping, it was just the convention used for these examples.

**Comment by keforbes** [comment]
I'm going to close this issue because I believe the desired behavior can be achieved using `<Plug>`.  Feel free to re-open if you have more problems though.
