### ISSUE TITLE
Commands (: and /) trigger file corruption through macros

### ISSUE THREAD

**Issue by coderkun** [vrapper/vrapper#817]
In Eclipse 4.9 (latest release currently) pressing the colon key in the default Eclipse editor to run a command behaves strangely by inserting (random?) text into the file but not showing the command popup. The slash key to search for text is also showing the popup only on second press. Especially the first one makes Vrapper unusable.

**Comment by keforbes** [comment]
What?? Eclipse is doing *two* releases in a single year?!? :scream: 

I had no idea they would be releasing a new version in September.  Vrapper is working fine for me in 4.8 (Photon, June release).  Can you check the Eclipse error log and see if you can find any stack traces with `net.sourceforge.vrapper` in them?  I wonder if this new version of Eclipse actually changed the API somewhere.

To find the error log, go to Help -> About Ecilpse IDE -> Installation Details -> Configuration -> View Error Log.

**Comment by keforbes** [comment]
I just installed the 2018-09 release, installed Vrapper, then created an untitled text file for testing.  I can bring up both the `:` and `/` modes just fine.  So please let me know what stack traces you're seeing on your side.

**Comment by albertdev** [comment]
How odd... First the log starts with this:

```
!ENTRY net.sourceforge.vrapper.eclipse 1 0 2018-09-24 17:17:04.751
!MESSAGE No .vrapperrc or _vrapperrc found.
```
So no `.vrapperrc` seems to get loaded which removes one potential source of errors. Then we get the first error somewhat later:

```
!ENTRY org.eclipse.ui 4 0 2018-09-24 17:17:15.282
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at net.sourceforge.vrapper.keymap.vim.ConstructorWrappers.parseKeyStrokes(ConstructorWrappers.java:71)
	at net.sourceforge.vrapper.vim.commands.PlaybackMacroCommand.execute(PlaybackMacroCommand.java:45)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.executeCommand(CommandBasedMode.java:264)
at net.sourceforge.vrapper.vim.modes.CommandBasedMode.handleKey(CommandBasedMode.java:318)
```

I can't remember that we bound macro's by default and yet here it seems to be executing one which it cannot parse.

You weren't by any chance doing something with macros?

**Comment by coderkun** [comment]
I wasn’t doing anything with macros before, no. And since I deleted all files to test with a fresh installation, I wonder where these would be saved. If it works for you with Eclipse 4.9 without issues, it might be an issue with my environment, though I have the same issue on my laptop as well …

Any idea how to proceed? Is there anything I can do or log?

**Comment by coderkun** [comment]
@keforbes, thanks for looking into this. It seems indeed to be releated to the keyboard layout: Usually I use the German [Neo](http://neo-layout.org/) layout and with that I have the mentioned issues, switching to the default German layout Vrapper behaves fine. What I don’t understand is that is was working fine under Eclipse 4.8, the update to Eclipse 4.9 broke it.

Any ideas?

`:registers` shows
![registers](https://user-images.githubusercontent.com/5249815/46026098-c84a6880-c0ea-11e8-9827-d3acb91a758b.png)

**Comment by albertdev** [comment]
Ahhh, I already had a feeling that you might be using the Qwertz or Neo keyboard layout based on your Github profile.

We have seen it before that Eclipse does weird things with "foreign" keyboard layouts, for example in the way the <kbd>@</kbd> char requires you to press <kbd>Alt Gr</kbd><kbd>Q</kbd>and where Eclipse detects it as <kbd>Alt</kbd><kbd>@</kbd>. Likely they recently changed it again...

[If I understand this right](https://neo-layout.org/index_en.html) you are in this case pressing the Caps Lock key or the <kbd>\ |</kbd> "international key" next to the Enter key as "mod3" in combination with the <kbd>d</kbd> key (<kbd>; :</kbd> on QWERTY) to get <kbd>:</kbd>.

At this point I haven't got the faintest idea how Eclipse detects this, I'll have to install the Neo layout myself to try it with a debugger attached...

**Comment by keforbes** [comment]
I don't know if this matters, but there was a change in 4.9 to handle <kbd>Alt Gr</kbd> differently.
https://www.eclipse.org/eclipse/news/4.9/platform_isv.php#alt-gr-display-post

**Comment by coderkun** [comment]
@keforbes, @albertdev, any idea how to fix this? Is anybody experience similar issues with “non-standard” keyboard layouts?

**Comment by konradsa** [comment]
I really hope Vrapper is not abandoned. This issue with randomly inserting text is driving me crazy, and it's not just annoying, it's plain dangerous, as it leaves code fragments in places they shouldn't be. I am glad other people have been observing it too, I was afraid it was just my issue.

I have been plagued by this since at least Oxygen, so not sure if it's just related to Photon. I run Eclipse either on a remote Linux host or local under WSL, same issue. I tried different X servers under Windows 10, issue still the same. There is nothing special about my setup, plain old QWERTY keyboard, nothing non-standard. The problem doesn't happen all the time, sometimes, it's fine for days, but when it starts it won't stop until I reboot machine.

**Comment by keforbes** [comment]
> I really hope Vrapper is not abandoned.

Honestly, it is basically abandoned.  The only two developers left (@albertdev and myself) don't use Eclipse anymore in our day jobs so we don't spend any time with Vrapper.  Also, the project has matured to the point that only the *really* tough defects are remaining and we simply don't have enough free time to dedicate to those problems.

> The problem doesn't happen all the time, sometimes, it's fine for days, but when it starts it won't stop until I reboot machine.

Next time the problem happens, can you check the Error Log to see if it's the same stack trace @coderkun is seeing?  That's strange for yours to be intermittent.

**Comment by albertdev** [comment]
@konradsa We did once get a report where someone was saying that sometimes files get "corrupted" in issue #794. That issue was also likely for Oxygen as it was logged on September 24, 2017.

We never were able to reproduce it due to the rather vague description, and it might or might not be related at all to the issue described above by *coderkun*.

Just to be sure though: are you using the GTK3 build of Eclipse?

**Comment by konradsa** [comment]
@albertdev Yes, I am using GTK3 version. Should be very easy to get WSL working, just install Ubuntu from the Store. You need to also install an X server, I recommend https://sourceforge.net/projects/vcxsrv/. Then unzip the Linux Eclipse archive and start eclipse executable, that's it.

If I remember correctly, the issue of commands not working and losing focus after opening a new file only been happening since I switched to GTK3 under Photon.  The issue with it inserting random characters has been happening for a little longer, definitely on GTK2 and Oxygen as well. That one is really about to drive me crazy, very bad. I really hope that can be fixed. Thanks so much in advance for looking into this.

**Comment by konradsa** [comment]
@albertdev Hi, any luck with reproducing the issues? Heavy heartedly I have disabled vrapper now in my Eclipse installation. I am missing it very much, but it's just too disruptive to my workflow.

**Comment by albertdev** [comment]
@konradsa I haven't gotten any further on this due to a multitude of reasons (including being sidetracked by work and other hobbies), but at least I can actually run Eclipse 4.9 in WSL now. While I must admit that it's a glitch fest where the command line will occasionally refuse to show itself and accept input, I haven't spotted any "file corruption" so far.

The only explanation I can offer for now as to a root cause is that maybe something's sending keystrokes with a nul-byte in the keypress event, in which case [it could be interpreted by Vrapper as pressing the @ key](https://github.com/vrapper/vrapper/blob/a8e129607b6ac77e0b93967a7dd5a5949e685a63/net.sourceforge.vrapper.eclipse/src/net/sourceforge/vrapper/eclipse/interceptor/VimInputInterceptorFactory.java#L205) (this was actually designed to detect a <kbd>Ctrl+@</kbd> keystroke). If this is true, the next keypress would then trigger the macro with that name and hence cause havoc when the given register contains a bunch of non-macro code.

Did you happen to find any new stacktraces related to Vrapper in the Eclipse logs? It could really help if it would bring new facts.

**Comment by albertdev** [comment]
Well well, it has paid off to egg me on. Eclipse 4.9 did introduce the `ALT_GR` key, and it has a very bad effect on Vrapper.

Once I managed to get VcXsrv to accept the Neo keyboard layout it quickly became obvious what @coderkun 's main problem could be: the Neo layout uses Alt Gr to implement "layer 3", then some ancient code of mine in 51deea3b49bcc5890ce171421d17ecb07c2644a9 sees the new `ALT_GR` key event introduced in Eclipse 4.9 and treats it as if it were a keypress of `@`. Whatever key you then press next will run whatever is in the register with that key's name as if it were a macro, hence corrupting your document. I've added some new code which should detect all possible modifiers and excludes those from processing. I still wasn't able to press `:` to open the console (it would always see that triangular character from "layer 6"), but that might have something to do with the complexity of the Neo layout and my WSL setup.

As to how this could occur in previous versions on a regular keyboard: if you press a 'special' key which Vrapper doesn't know anything about (e.g. Scroll Lock, Sys Rq / Break, ...) it would also be interpreted as `@` and might hence also run more macros when you least expect it.

All of this at least offers some explanation for the things we have seen above. The only thing I haven't figured out yet is why GTK3 has problems with its first time opening the command line inside an editor. Once you've regained control by clicking the mouse inside the editor and pressed Escape, the console seems to open and close fine. This is one of those things which is impossible to debug on Windows as it has been working fine there for ages. It is going to take quite some more time to troubleshoot that part...

**Comment by coderkun** [comment]
> Once I managed to get VcXsrv to accept the Neo keyboard layout it quickly became obvious what @coderkun 's main problem could be: the Neo layout uses Alt Gr to implement "layer 3", then some ancient code of mine in 51deea3 sees the new ALT_GR key event introduced in Eclipse 4.9 and treats it as if it were a keypress of @. Whatever key you then press next will run whatever is in the register with that key's name as if it were a macro, hence corrupting your document.

That sounds exactly like the issue I experience!

> I've added some new code which should detect all possible modifiers and excludes those from processing.

You are referring to bb5db4d, right? I will check it out and test it.

> I still wasn't able to press : to open the console (it would always see that triangular character from "layer 6"), but that might have something to do with the complexity of the Neo layout and my WSL setup.

I will test this in my environment and report back.

Thanks a lot for looking into this!

**Comment by coderkun** [comment]
@albertdev, I checked out the master branch (bb5db4d1) and followed [Setup eclipse to develop vrapper](https://github.com/vrapper/vrapper/wiki/Setup-eclipse-to-develop-vrapper) to test it. In the new Eclipse instance Vrapper is working much better and I can use it again. Things like open the command mode/input line work again and no random macro stuff is executed.

So I can confirm that my issue has been fixed by your change.

**Comment by keforbes** [comment]
@coderkun, thanks for testing out @albertdev's change!  I'm glad to hear it worked for you.  I've updated the unstable update site with this build so you can install it in your regular eclipse environment.  Just add the unstable update site (http://vrapper.sourceforge.net/update-site/unstable) to your eclipse and then run Check For Updates and it should find 0.73.20181120.

**Comment by keforbes** [comment]
@konradsa, I should've tagged you in my previous comment as well.  Please try updating to the latest build on the unstable update site and see if it resolves your issue.  Thanks!

**Comment by coderkun** [comment]
Thanks a lot, @keforbes (and @albertdev)! I am finally able to use Vrapper again for daily work in regular Eclipse.

**Comment by albertdev** [comment]
I'm closing this issue as a fix has been delivered in the next build. There is still the issue of the command line being invisible the first time it's opened in an editor, but there's already a different issue for that.

**Comment by konradsa** [comment]
@albertdev Thanks so much. Unfortunately my employer blocks sourceforge completely. So if you could name a release zip available somewhere, that would be appreciated!

**Comment by albertdev** [comment]
Yeah, @keforbes has been diligently adding zip files to the [Github vrapper project releases page](https://github.com/vrapper/vrapper/releases) ever since Sourceforge started acting very spotty.
