### ISSUE TITLE
executing macro ignores eclipseuiaction

### ISSUE THREAD

**Issue by thomasrebele** [vrapper/vrapper#818]
I wanted to use a vrapper macro with an eclipse action to refactor Java code. The eclipse action moves the cursor to the definition of the variable under the cursor.

Here the content of .vrapperrc
```
eclipseuiaction eclipsegotodef org.eclipse.jdt.ui.edit.text.java.open.editor
nnoremap ld :eclipsegotodef<cr>
```

When I try a macro that only executes `ld`, it works as expected, i.e., the cursor jumps to the definition.
However, when I add a motion, e.g., `ldb`, it only executes the motion. Expected behavior: the cursor jumps to the definition, and then executes the motion.

PS: thanks for the great plugin!

--- addendum ---
I tried to include a short break, hoping that vrapper would then use the right starting position for the motion, but to no avail.
try 1: `:eclipsegotodef<cr>:r!sleep 2<cr>b`
try 2: `:eclipsegotodef|r!sleep 2<cr>b`

**Comment by keforbes** [comment]
Hm, weird.  I tried a couple other alternatives, like:
```
:nnoremap ld :eclipsegotodef | normal b<cr>
```
and
```
:nnoremap ld :eclipsegotodef<cr>normal b<cr>
```
but those just cause the editor to lose focus after highlighting the definition. :man_shrugging: 

Of course, using
```
nnoremap ld :eclipsegotodef<cr>
```
and then just hitting `b` works exactly as expected (with the same number of keystrokes) but I understand wanting the cursor in the right spot after a jump

**Comment by thomasrebele** [comment]
I had a look at vrapper's source code. Apparently `eclipseuiaction` is executed asynchronous. I switched it to `eclipseaction`. The macro then jumps to the definition, but ignores subsequent motions.

**Comment by thomasrebele** [comment]
on my personal computer it works as expected. I'll try again tomorrow.

**Comment by albertdev** [comment]
I wanted to propose using a `<Plug>(eclipse-motion:org.eclipse.jdt.ui.edit.text.java.open.editor)` mapping, as this indicates more clearly to Vrapper that you want a jump action.

What might be going wrong is that the `ld` action moves the editor's caret, but the `b` motion somehow captures the previous position and then puts the editor's caret at the previous position but on word back. This should not happen as easily with the `<Plug>` I wrote above.

Do keep in mind that the command id seems to indicate that this action can switch editors. It's thus very likely that your macro will never work when you jump to a different file: each Eclipse editor runs its own copy of Vrapper so the rest of the macro after the `ld` action or plug would be executed in the original editor rather than the newly focused editor.

**Comment by thomasrebele** [comment]
I should have restarted eclipse cleanly before testing `eclipseaction`. Today the macro executes as expected using `eclipseaction`, i.e., the cursor finishes at the expected position. However, I cannot type in anything afterwards.

@albertdev: thanks, `nnoremap ld <Plug>(eclipse-motion:...)` works like a charm. I'm closing the issue as this workaround solves my problem.
