### ISSUE TITLE
The cursor disappears!

### ISSUE THREAD

**Issue by zrsharp** [vrapper/vrapper#829]
**Problem:** 
When triggering a floating window,  for example, I press \<F2\> or trigger a code prompt, and then I press \<ESC\> to close the floating window, the cursor will disappear. And after that, if I perform :w to save file, the cursor will also disappear. Only if I use mouse to click white space  rather than press \<ESC\>, the cursor will not disappear.

My eclipse version is 4.15.0,
OS is archLinux, 
wm is i3wm.

**Pictures:** 
1. I trigger a floating window:
![image](https://raw.githubusercontent.com/zrsharp/issuePictures/master/vrapper-vrapper1.png)

2. After press \<ESC\> the cursor disapper.
![image](https://raw.githubusercontent.com/zrsharp/issuePictures/master/vrapper-vrapper2.png)

**Others**:
If I use a mouse in some places， the  result will be different. Such as when cursor disappear, I click some places, the cursor will appear again!!!  And different operations make results different. This makes me uncomfortable! Maybe I just want to use the keyboard. Could you help me? Please.
 I need it.

**Comment by albertdev** [comment]
Thank you for putting so many details in your issue. It does seem you forgot to include your Vrapper version, which you can find by going to Help -> About Eclipse IDE -> Installation Details -> Configuration -> Installed Plugins.

Sadly, UI glitches like these are hard to reproduce for us at the best of times. For example, it is also possible that they happen only on your particular Eclipse version on your particular system rather than Vrapper. Have you tried what happens when you disable Vrapper and tried doing similar UI actions?

If it happens without Vrapper as well then you might need to check on Eclipse's bugtracker.

**Comment by keforbes** [comment]
Also, can you check the Eclipse Error Log to see if there are any stack traces with  `net.sourceforge.vrapper` in them?  To find the error log, go to Help -> About Ecilpse IDE -> Installation Details -> Configuration -> View Error Log.

**Comment by zrsharp** [comment]
Oh My God! It's my fault. It still happens after the vrapper plug-in is closed. It seems that this should be the problem of eclipse, or the problem of my system environment. Once I installed eclipse, I installed vrapper. So I didn't think about it.Thank you for your help!
