### ISSUE TITLE
Ctrl + u does not work for half-page up, but Ctrl + Shift + u works.. Why? 

### ISSUE THREAD

**Issue by earik87** [vrapper/vrapper#834]
I unbinded all Ctrl+u keybindings from eclipse. Ctrl+u does not work but Ctrl+Shift+u works. Why this is happening? 

However, Ctrl+d works fine for half-page down. Is there another keybinding of Ctrl+u that I cannot see on eclipse? This is very strange.

Op. System = Windows 10.

**Comment by keforbes** [comment]
I'm not sure what to tell you.  <kbd>Ctrl+u</kbd> works fine for me and does half-page up.  If you search Eclipse's key bindings for `Ctrl+u` and there aren't any matches then I'm not sure what would be stealing that key press.  Are you on the latest version of Eclipse and the latest version of Vrapper?

**Comment by albertdev** [comment]
Does anything happen in Eclipse when you press <kbd>Ctrl</kbd>+<kbd>u</kbd>? If not then I would recommend actually binding it in the Eclipse preferences to some action which opens a window and seeing if that works.

The reason is that recently I got frustrated that some hotkeys would never work. It turned out that some other program running in the background had registered that hotkey _globally_ and so would intercept that hotkey no matter what application is running in the foreground. Once I knew what was happening it was obvious that the background program was changing state due to the global shortcut, but it took me a couple of hours to get there...

Of course, _if_ this would be the case then we can't really help you, but please do give it a try. It shouldn't take much time to do it.

**Comment by earik87** [comment]
Thanks for all the comments. It was indeed a **hotkey**. U is assigned as number '4'. And by chance, f10 (num lock) was on when I was having this issue. I disabled the num lock which assigns U to 4. Now Ctrl + U works as half page up!

I am closing the issue. And special thanks for the people who made this greate plugin!
