### ISSUE TITLE
Cannot install in eclipse 2020-06 (4.16.0)

### ISSUE THREAD

**Issue by eugene-so** [vrapper/vrapper#838]
Using OSX catalin 10.15.6
java version "14.0.2" 2020-07-14 

I get this error message when trying to install vrapper:

Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 9.0.0
  Software currently installed: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
  Cannot satisfy dependency:
    From: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tools.templates.freemarker.java11 [1.1.100.202001140305,1.1.100.202001140305]
  Cannot satisfy dependency:
    From: Template Engine Freemarker Support (Java 11) 1.1.100.202001140305 (org.eclipse.tools.templates.freemarker.java11 1.1.100.202001140305)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))

**Comment by keforbes** [comment]
I wonder if the issue is that we're still compiling with Java 8.  You have Java 14 and it looks like it's trying to install Java 9 (I assume for Java 8 support) and it's failing.

Wikipedia says:
> As of March 2020, Java 8 and 11 are supported as Long Term Support (LTS) versions

We could probably look into moving to Java 11.  Hopefully that would be a good lowest-common-denominator with all our users.

**Comment by eugene-so** [comment]
I tried Java 8 and 9 as well and get similar installation errors.

**Comment by eugene-so** [comment]
Wonder if it has something to do with this AutoTools dependency.  I will look into it as well.

**Comment by eugene-so** [comment]
Looks like it may be related this this issue: https://github.com/espressif/idf-eclipse-plugin/issues/102.  I will test it out by reinstalling eclipse using my latest Java.

**Comment by eugene-so** [comment]
I'm confirming that espressif/idf-eclipse-plugin#102 was the problem, so it was an issue with eclipse 2020-06 rather than vrapper.  Reinstalling eclipse after i had installed java 14 fixed the issue.

**Comment by keforbes** [comment]
I'm glad you figured it out! (And I'm glad it wasn't Vrapper's fault.)

**Comment by albertdev** [comment]
> 
> 
> I wonder if the issue is that we're still compiling with Java 8. You have Java 14 and it looks like it's trying to install Java 9 (I assume for Java 8 support) and it's failing.
> 
> Wikipedia says:
> 
> > As of March 2020, Java 8 and 11 are supported as Long Term Support (LTS) versions
> 
> We could probably look into moving to Java 11. Hopefully that would be a good lowest-common-denominator with all our users.

As a matter of fact, compiling with al older version of Java is not an issue. Since the Java Virtual Machine team tries to keep older binaries compatible, existing libraries will keep working. The only real incompatible change we've seen recently is the step between Java 8 and 9 where an entirely new module system was invented.

However, Eclipse has been using OSGi under the hood for decades, and since OSGi is a module system layered on top of different versions of the JVM it will actually handle things for us.

The supported versions you found above are rather the versions of Java which you are supposed to install on client machines: bugs and other security issues can be found in the JVM, and only those two versions will have free long-term support. Any other version can be run, but at your own risk. But really, we only need the compiler from a Java 7 install, there's no need to run that JVM.

So the only drawback we have of sticking to Java 6 or 7 as compilation target is that we cannot use newer language features. Since Vrapper development is stalled, we might not actually miss that much...
