### ISSUE TITLE
Replacing something with forward slashes

### ISSUE THREAD

**Issue by JanFeld** [vrapper/vrapper#844]
Hi,

i'm using Vrapper v`0.74.0 in STM32CubeIDE (Eclipse based) on mac.

I've tried to add the following pattern to the end of every selected line: `//-`.

I've tried two methods:

```'<,'>s/$/\/\/-/g```
and 
```'<,'>norm A//-```

which both failed.

The first one added *exactly* the string `\/\/-` and the second one inserted the number of lines i've selected in visual mode with `rm A//-`.

When trying these commands in regular vim they are working like intended.

Cheers,
Jan

**Comment by keforbes** [comment]
I'll see if I can figure out why it's behaving incorrectly, but for the time being, here's a workaround.

You can actually use any character after the `s` to represent the substitution delimiter (just like in vim).  So you if you use a `,` rather than a `/` as the delimiter it'll perform the correct substitution:
```
:'<,'>s,$,//-,g
```

**Comment by JanFeld** [comment]
Thanks for the workaround!
Never thought of this.

Thanks!

**Comment by keforbes** [comment]
You don't care about what's happening under the hood but I'm going to provide an explanation anyway.

So the reason your first attempt included the escape `\` characters is because I'm using Eclipse's regex engine under the hood.  That engine doesn't handle a regex of just `^` or `$` so I have a special case where if the search string is just `^` I insert the replace string at the beginning of the line and if the search string is just `$` I insert the replace string at the end of the line.  This means I'm just blindly inserting the replace string itself, I'm not interpreting escape characters.  I should probably add a quick "remove the `\` characters" step in those cases.

Your second attempt with `norm` is a really stupid defect.  Vrapper is detecting that the requested operation is a `norm` but then it's trying to slice off the `norm` part of the command string to leave behind the actual operation.  That code isn't expecting to see `'<,'>` so it's throwing off the slice index and leaving behind the `rm` part of `norm`. :roll_eyes:  Just a simple `:norm A//-` works fine when there's no range selection prefix.  And for some reason, `'<,'>normal A//-` works fine too.

I'll see what I can do about fixing both these issues but I'm glad you've got a workaround so you aren't blocked by this anymore.

**Comment by JanFeld** [comment]
Actually i didn't try to have a look into the code, you're right regarding no interest in 'implementational detail' by now.

But the explanations seem quite interesting and help me to understand what's going on. 
Thanks for that.

P.S.: Maybe you can give me a hint in another topic.. I'm often trying to edit multiple lines with the same changes at the same position.
In vim i'd just go with `ctrl+v`. Is there any way to avoid eclipse to catch this as paste..? Is it as simple as changing a shortcut/keybinding or is it not implemented anyway because of this?

**Comment by keforbes** [comment]
> In vim i'd just go with ctrl+v. Is there any way to avoid eclipse to catch this as paste..? Is it as simple as changing a shortcut/keybinding or is it not implemented anyway because of this?

That's exactly right, it's a keybinding.
http://vrapper.sourceforge.net/documentation/?topic=commands

Eclipse always steals any `Ctrl` commands before passing them down to any plugins.  So you need to unbind any `Ctrl` commands for Vrapper to receive them.  In Eclipse (not sure if STM32CubeIDE is the same) you would go to Window -> Preferences -> General -> Keys.  There should be a Scheme dropdown at the top which is currently set to Default.  You can change that to "Vim's key bindings" and I think that should work.  Someone else contributed that scheme for us so I've never really used it.  It was added years after I already got into the habit of searching for `Ctrl+V` and simply clicking the "Unbind Command" button.  Either way should work though.  Personally, I like explicitly unbinding the few `Ctrl` commands I use in Vim since I don't use too many of them.

**Comment by JanFeld** [comment]
That's great! Thank you again. The key-binding option is exactly what i hoped to get. Never thought of checking the option for changing the whole bindings.

**Comment by keforbes** [comment]
No problem!  Vrapper may seem dead but that's mostly because it's a mature project and already handles most cases.

Also, I mentioned the "Vim's key bindings" Scheme earlier.  That was actually added after version 0.74.0.  You would have to add the unstable update site (`http://vrapper.sourceforge.net/update-site/unstable`) to Eclipse then "Check for Updates" to get the latest build.  I've gotten lazy and haven't done a full "release" in a couple years but I still rebuild the unstable update site with every commit.

**Comment by JanFeld** [comment]
Then i'm wondering if i got the version wrong ... I found the key-map but eclipse shows that i've installed 0.74.0 .. I didn't check any nightly/unstable release-branches. 

Nevertheless, i'm more than happy now. I love using vim but i'm somewhat bound to these IDEs. I'm grateful to be able to use Vrapper. Thanks for your and all the contributors work!
