### ISSUE TITLE
Cleanup project

### ISSUE THREAD

**Issue by frankbenoit** [vrapper/vrapper#865]
Hi,

I want to offer to do some cleanup in the project to ease future development.

1. Make use of [CBI target platform DSL](https://github.com/eclipse-cbi/targetplatform-dsl), to define a target platform that is used for development, instead of just using the running Eclipse IDE as developement basis
2. Make use of the [LC DSL](https://github.com/ssi-schaefer/lcdsl), a tooling to define a launch configuration.
3. Adjust the project layout to standard folders: features, plugins, tests, releng
4. Raise Java from 1.6 to Java 17, because Eclipse has it meanwhile as minimum requirement
5. Fix the warnings in the code
6. Create a maven build that can be used as automatic build on Github and make it easier to create a release
7. An oomph setup to automate setting up Eclipse for development.

Would such PRs be welcome?

regards Frank

**Comment by keforbes** [comment]
Absolutely, yes!  Is there anything I can do to help facilitate you?  Like create a new branch that you can push your work to as you go?  It doesn't have to be one massive PR.

**Comment by frankbenoit** [comment]
Thanks for response. I will try to create small PRs, to minimize risk and make review hopefully easy.

**Comment by frankbenoit** [comment]
@keforbes i am done with preparation of those tasks:
Java17, folder layout, maven build, fix most warnings.
Maven now runs the test, and build the complete update site is build as a zip in one shot.

### Failing test
There is one unit test that fails: VrapperRCTests. Is it expected to work?
The file reader is missing a character set. I found `x-MacCentralEurope` for the `sample.vrapperrc`.
Any doubts if i change the file to utf8?

### Feature names
I am going to name the features with ".feature", so they are consistent with what I know from other projects.

### Test project dependencies
There is some tricks to make the classes visible for testing: `Eclipse-BuddyPolicy: dependent` and the special rule in `n.s.v.core.tests/.classpath`
I am going to remove those and instead split out a separated test bundle for `surround` and a `testutil` with the base classes.
The test bundle to be a fragment from the bundle under test.
That way, the dependencies are just standard `Require-Bundle`.

### Fragment cdt/jdt
I wonder why it is done as fragments and not just regular plugins?

### Just update-site vs stable/unstable
Normally I see project just having one update-site, which might be called stable/unstable. 
However IMO there is no need to have those in parallel in the code base.


![image](https://github.com/vrapper/vrapper/assets/8962790/f5a3f09f-5eee-4c72-a1ad-ebac8e693e19)

**Comment by albertdev** [comment]
> Raise Java from 1.6 to Java 17, because Eclipse has it meanwhile as minimum requirement

Mind you that we kept the Java target version so low to support ancient versions of Eclipse.
If JDT can compile classes to e.g. Java 8 or 9 support then we don't need to rule those out.

What is the oldest (supported) Eclipse version by now which still gets platform updates if needed?

**Comment by frankbenoit** [comment]
What shall be the oldest Eclipse version, where new Vrapper releases shall be installable?

**Comment by keforbes** [comment]
> What shall be the oldest Eclipse version, where new Vrapper releases shall be installable?

This is a tough question to answer because there are some tools that are built with Eclipse as the base and I can't guarantee those tools are built on a reasonable version of Eclipse.  Also, we have a Split-Editor plugin which relies on the Eclipse 4 API and we made that a separate plugin because (at the time) the majority of our users were stuck on Eclipse 3.x for longer than expected.

I'd like to say we only need to support whatever versions Eclipse still supports, but I honestly can't find what Eclipse claims for long-term support.  At least this [older versions of Eclipse](https://wiki.eclipse.org/Older_Versions_Of_Eclipse) page goes back to Eclipse 4.7.2 (2017) and their [archive](https://archive.eclipse.org/eclipse/downloads/index.php) page is for all versions before that.  That archive page specifically says Luna (Eclipse 4.4) supports Java 8.

With that said, it's been 5 years since the latest "stable" build of Vrapper (installable from the Eclipse Marketplace) and 3 years since the latest "unstable" build (which people have to go out of their way to install).  Despite the fact that we still get [1,000+ installs every month](https://marketplace.eclipse.org/content/vrapper-vim#metrics), we really haven't had a big push for new features or support.

Given that both myself and @albertdev don't deal with Eclipse anymore, I'm tempted to just give you free rein to make whatever changes you want in the repo.  I don't have any intentions of working on this project anymore so I'd be happy to hand it over if you're willing to update it.  @albertdev, do you have any concerns?

**Comment by albertdev** [comment]
> I don't have any intentions of working on this project anymore so I'd be happy to hand it over if you're willing to update it. @albertdev, do you have any concerns?

I'll admit we could use help - I've not been spending any time on this plugin other than occasionally poking my head into github issues.

At the same time I haven't even got access to most of the Eclipse Marketplace, and then handing control over to a "new" person seems a bit sudden, especially if we still have hundreds of installs per month?

I wouldn't mind reviewing PRs for the short term, and discussing what the plan for "future development" exactly entails.

**Comment by frankbenoit** [comment]
My intend is not to take the project. It is more the wish to make Vrapper more attractive to developers who might want to jump in here and there (perhaps I might do).

My opinion about Java update: Users of ancient Eclipse version can always use the old version of Vrapper. This worked for many year now.
But for the Vrapper project, finding contributors is essential. Hence going to an up to date state is probably a good thing. 
If users of an ancient version need a specific bug fix, a back port is is always technically possible with a 0.74.1 release.

**Comment by keforbes** [comment]
I agree, users can stay on an older version if there are issues with compatibility, especially if we aren't introducing new features as part of this restructuring.

I'm of the opinion that you should just make whatever changes you feel are necessary.  We can always revert any changes that cause problems.
